<?php

/**
 * Implements hook_requirements().
 */
function membersify_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $t = get_t();

    if (!function_exists('curl_init')) {
      $requirements['membersify_curl'] = array(
        'severity' => REQUIREMENT_ERROR,
        'title' => $t('cURL'),
        'description' => $t('Membersify needs the CURL PHP extension.'),
        'value' => $t('Not found'),
      );
    }

    if (!function_exists('json_decode')) {
      $requirements['membersify_json_decode'] = array(
        'severity' => REQUIREMENT_ERROR,
        'title' => $t('JSON'),
        'description' => $t('Membersify needs the JSON PHP extension.'),
        'value' => $t('Not found'),
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function membersify_uninstall() {
  // Delete related variables all at once.
  db_delete('variable')
  ->condition('name', 'membersify_%%', 'LIKE')
  ->execute();
}

/**
 * Implements hook_schema().
 */
function membersify_schema() {
  $schema['membersify_plans'] = array(
    'description' => 'Plans',
    'fields' => array(
      'id' => array(
        'type' => 'varchar',
        'description' => 'The plan id.',
        'length' => '16',
        'not null' => TRUE,
      ),
      'livemode' => array(
        'description' => 'Livemode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'name' => array(
        'type' => 'varchar',
        'description' => 'The name of the plan.',
        'length' => '255',
        'not null' => TRUE,
      ),
      'type' => array(
        'type' => 'varchar',
        'description' => 'The type',
        'length' => '128',
        'not null' => TRUE,
        'default' => '',
      ),
      'machine_name' => array(
        'type' => 'varchar',
        'description' => 'The machine name',
        'length' => '128',
        'not null' => TRUE,
        'default' => '',
      ),
      'description' => array(
        'type' => 'text',
        'description' => 'Description of the plan.',
      ),
      'weight' => array(
        'type' => 'int',
        'description' => 'Weight',
        'not null' => TRUE,
        'default' => 0,
      ),
      'payment_plan' => array(
        'type' => 'text',
        'description' => 'The payment plan.',
        'serialize' => TRUE,
      ),
      'data' => array(
        'type' => 'text',
        'description' => 'Data for the plan.',
        'serialize' => TRUE,
      ),
    ),
    'unique keys' => array(
      'id' => array('id'),
    ),
  );

  $schema['membersify_subscriptions'] = array(
    'description' => 'Subscriptions',
    'fields' => array(
      'id' => array(
        'type' => 'varchar',
        'description' => 'The unique key.',
        'length' => '16',
        'not null' => TRUE,
      ),
      'user_id' => array(
        'type' => 'int',
        'description' => 'The user ID.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'display' => array(
        'type' => 'varchar',
        'description' => 'The display text.',
        'length' => 256,
        'not null' => TRUE,
        'default' => '',
      ),
      'custom' => array(
        'type' => 'varchar',
        'description' => 'The custom variable.',
        'length' => 256,
        'not null' => TRUE,
        'default' => '',
      ),
      'plan_id' => array(
        'type' => 'varchar',
        'description' => 'The plan ID.',
        'length' => '32',
        'not null' => TRUE,
        'default' => '',
      ),
      'payment_profile_id' => array(
        'type' => 'varchar',
        'description' => 'The profile id.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'livemode' => array(
        'description' => 'Livemode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'status' => array(
        'type' => 'varchar',
        'description' => 'The status of the subscription.',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
      ),
      'expiration' => array(
        'type' => 'int',
        'description' => 'The expiration date of the subscription.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'start_date' => array(
        'type' => 'int',
        'description' => 'The start date for the subscription.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'current_payments' => array(
        'type' => 'int',
        'description' => 'The current number of payments made.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'current_period_start' => array(
        'type' => 'int',
        'description' => 'When the current period started.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'next_payment' => array(
        'type' => 'int',
        'description' => 'When the next payment will be processed.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'total_occurrences' => array(
        'description' => 'The total number of payments until expiration.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'payment_plan' => array(
        'type' => 'text',
        'description' => 'The payment plan.',
        'serialize' => TRUE,
      ),
      'failed_payments' => array(
        'description' => 'The number of failed payments in a row.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'unique keys' => array(
      'id' => array('id'),
    ),
  );

  $schema['membersify_history'] = array(
    'description' => 'History items.',
    'fields' => array(
      'id' => array(
        'type' => 'varchar',
        'description' => 'The unique key.',
        'length' => '64',
        'not null' => TRUE,
      ),
      'subscription_id' => array(
        'type' => 'varchar',
        'description' => 'The id of the subscription.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'livemode' => array(
        'description' => 'Livemode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'type' => array(
        'type' => 'varchar',
        'description' => 'The item type.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'txn_id' => array(
        'type' => 'varchar',
        'description' => 'Transaction ID.',
        'length' => '128',
      ),
      'amount' => array(
        'type' => 'numeric',
        'description' => 'The amount that was paid.',
        'not null' => TRUE,
        'precision' => '10',
        'scale' => '2',
      ),
      'currency' => array(
        'type' => 'varchar',
        'description' => 'The currency code used for the payment.',
        'length' => '32',
      ),
      'created' => array(
        'type' => 'int',
        'description' => 'When the payment was created.',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'unique keys' => array(
      'id' => array('id'),
    ),
  );

  $schema['membersify_payment_profiles'] = array(
    'description' => 'Payment profiles',
    'fields' => array(
      'id' => array(
        'type' => 'varchar',
        'description' => 'The profile id.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'user_id' => array(
        'type' => 'int',
        'description' => 'The user id.',
        'not null' => TRUE,
        'default' => 0,
      ),
      'livemode' => array(
        'description' => 'Livemode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'display' => array(
        'type' => 'varchar',
        'description' => 'The display string.',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
      ),
      'status' => array(
        'type' => 'varchar',
        'description' => 'The status of the subscription.',
        'length' => '255',
        'not null' => TRUE,
        'default' => '',
      ),
    ),
    'unique keys' => array(
      'id' => array('id'),
    ),
  );

  $schema['membersify_adjustments'] = array(
    'description' => 'Adjustments',
    'fields' => array(
      'id' => array(
        'type' => 'varchar',
        'description' => 'The unique key.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'livemode' => array(
        'description' => 'Livemode',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
      'object_type' => array(
        'description' => 'The adjustment object type.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'type' => array(
        'description' => 'The value type (percentage/fixed).',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'scope' => array(
        'description' => 'Whether the adjustment should apply to whole order or just first payment.',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => 'recurring',
      ),
      'display' => array(
        'description' => 'The label of the adjustment.',
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => '',
      ),
      'value' => array(
        'description' => 'The value of the adjustment.',
        'type' => 'numeric',
        'precision' => 16,
        'scale' => 5,
        'not null' => TRUE,
        'default' => 0.0,
      ),
      'weight' => array(
        'description' => 'How early to process the adjustment.',
        'type' => 'int',
        'size' => 'small',
        'not null' => TRUE,
        'default' => 0,
      ),
      'status' => array(
        'type' => 'varchar',
        'description' => 'The status of the adjustment.',
        'length' => '32',
        'not null' => TRUE,
        'default' => '',
      ),
      'optional' => array(
        'description' => t('Whether the adjustment is optional.'),
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => FALSE,
        'default' => 0,
      ),
      'data' => array(
        'type' => 'text',
        'description' => 'The data.',
        'serialize' => TRUE,
      ),
    ),
    'unique keys' => array(
      'id' => array('id'),
    ),
  );

  $schema['membersify_coupons'] = array(
    'description' => 'Coupons',
    'fields' => array(
      'adjustment_id' => array(
        'type' => 'varchar',
        'description' => 'The adjustment foreign key.',
        'length' => '32',
        'not null' => TRUE,
      ),
      'code' => array(
        'type' => 'varchar',
        'description' => 'The coupon code.',
        'length' => 40,
        'not null' => TRUE,
        'default' => '',
      ),
      'expiration' => array(
        'type' => 'int',
        'description' => 'The expiration date.',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'big',
      ),
      'used' => array(
        'type' => 'int',
        'size' => 'small',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'How many times the coupon has been used.',
      ),
      'max_uses' => array(
        'type' => 'int',
        'size' => 'small',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The maximum number of times a coupon can be used.',
      ),
      'minimum_order' => array(
        'type' => 'numeric',
        'precision' => 6,
        'scale' => 2,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The minimum order amount required.',
      ),
    ),
    'unique keys' => array(
      'adjustment_id' => array('adjustment_id'),
    ),
  );

  return $schema;
}

// ======================================
// Updates:
// ======================================

/**
 * Add the display field and rename the memberships table to subscriptions.
 */
function membersify_update_7100(&$sandbox) {
  db_add_field('membersify_memberships', 'display', array(
    'type' => 'varchar',
    'description' => 'The display text',
    'length' => '256',
    'not null' => TRUE,
    'default' => '',
  ));
  db_add_field('membersify_memberships', 'custom', array(
    'type' => 'varchar',
    'description' => 'The custom variable',
    'length' => '256',
    'not null' => TRUE,
    'default' => '',
  ));
  db_add_field('membersify_memberships', 'current_period_start', array(
    'type' => 'int',
    'description' => 'When the current period started.',
    'not null' => TRUE,
    'default' => 0,
  ));
  db_add_field('membersify_plans', 'type', array(
    'type' => 'varchar',
    'description' => 'The type',
    'length' => '128',
    'not null' => TRUE,
    'default' => '',
  ));
  db_add_field('membersify_plans', 'machine_name', array(
    'type' => 'varchar',
    'description' => 'The machine name',
    'length' => '128',
    'not null' => TRUE,
    'default' => '',
  ));

  db_change_field('membersify_history', 'membership_id', 'subscription_id', array(
    'type' => 'varchar',
    'description' => 'The id of the subscription.',
    'length' => '32',
    'not null' => TRUE,
    'default' => '',
  ));

  db_rename_table('membersify_memberships', 'membersify_subscriptions');

  // Re-sync everything.
  membersify_sync_all();
}