<?php

/**
 * Implements hook_services_resources().
 */
function nodequeue_services_services_resources() {
  $resources = array(
    'nodequeue_services' => array(
      'operations' => array(
        'retrieve' => array(
          'file' => array(
            'type' => 'inc',
            'module' => 'nodequeue_services',
            'name' => 'nodequeue_services_resources'
          ),
          'callback' => '_nodequeue_services_resource_retrieve',
          'args' => array(
            array(
              'name' => 'qid',
              'optional' => false,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'The id of the nodequeue to get',
            ),
          ),
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => false,
        ),
        'create' => array(
          'file' => array(
            'type' => 'inc',
            'module' => 'nodequeue_services',
            'name' => 'nodequeue_services_resources'
          ),
          'callback' => '_nodequeue_services_resource_create',
          'args' => array(
            array(
              'name' => 'nodequeue',
              'type' => 'struct',
              'description' => 'The nodequeue data to create',
              'source' => 'data',
              'optional' => false,
            ),
          ),
          'access callback' => 'user_access',
          'access arguments' => array('administer nodequeue'),
          'access arguments append' => false,
        ),
        'update' => array(
          'file' => array(
            'type' => 'inc',
            'module' => 'nodequeue_services',
            'name' => 'nodequeue_services_resources'
          ),
          'callback' => '_nodequeue_services_resource_update',
          'args' => array(
            array(
              'name' => 'id',
              'type' => 'int',
              'description' => 'The id of the nodequeue to update',
              'source' => array('path' => '0'),
              'optional' => false,
            ),
            array(
              'name' => 'data',
              'type' => 'struct',
              'description' => 'The nodequeue data object',
              'source' => 'data',
              'optional' => false,
            ),
          ),
          'access callback' => 'user_access',
          'access arguments' => array('administer nodequeue'),
          'access arguments append' => false,
        ),
        'delete' => array(
          'file' => array(
            'type' => 'inc',
            'module' => 'nodequeue_services',
            'name' => 'nodequeue_services_resources'
          ),
          'callback' => '_nodequeue_services_resource_delete',
          'args' => array(
            array(
              'name' => 'qid',
              'optional' => false,
              'source' => array('path' => 0),
              'type' => 'int',
            ),
          ),
          'access callback' => 'user_access',
          'access arguments' => array('administer nodequeue'),
          'access arguments append' => false,
        ),
        'index' => array(
          'help' => 'Retrieves a listing of nodequeues',
          'file' => array(
            'type' => 'inc',
            'module' => 'nodequeue_services',
            'name' => 'nodequeue_services_resources'
          ),
          'callback' => '_nodequeue_services_resource_index',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => false,
        ),
      ),
    ),
  );

  return $resources;
}