language: node_js
node_js:
  - 0.1
env:
  global:
  - SAUCE_USERNAME=aidaskk
  - SAUCE_ACCESS_KEY=6e96b47e-6665-4f69-beaa-085e5d5b6b9b
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma
  - npm install
script: grunt
