<?php
/**
 * @file
 * Install, update and uninstall functions for the ac_newsletter module.
 */

/**
 * Implements hook_requirements().
 */
function ac_newsletter_requirements($phase) {
  $requirements = array();

  if ($phase == 'install' || $phase == 'runtime') {
    $t = get_t();
    $library_link = l($t('ActiveCampaign API Php library'), 'https://github.com/ActiveCampaign/activecampaign-api-php', array(
      'attributes' => array('target' => '_blank')));
    if (!function_exists('libraries_get_path') || !libraries_get_path('activecampaign')) {
      $requirements['ac_newsletter_api_php'] = array(
        'title' => $t('ActiveCampaign API Php library'),
        'value' => $t('Not Installed'),
        'severity' => REQUIREMENT_ERROR,
        'description' => $t('You need to download the !ac-newsletter-api-php, Unpack and rename the library directory to "activecampaign" and place it inside the %path directory on your server.', array('!ac-newsletter-api-php' => $library_link, '%path' => 'sites/all/libraries')),
      );
    }
    else {
      $requirements['ac_newsletter_api_php'] = array(
        'title' => $t('ActiveCampaign API Php library'),
        'value' => $t('Installed'),
        'severity' => REQUIREMENT_OK,
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function ac_newsletter_uninstall() {
  // Query to fetch all available ac_newsletter variables.
  $query = db_select('variable', 'var');
  $query->fields('var', array('name'));
  $query->condition('var.name', db_like('ac_newsletter_') . '%', 'LIKE');
  $ac_newsletter_variables = $query->execute()->fetchcol();
  // Loop and delete the available ac_newsletter variables.
  foreach ($ac_newsletter_variables as $variable_name) {
    variable_del($variable_name);
  }
}
