<?php

/**
 * Implements hook_menu_link_update().
 */
function taxonomy_menu_extras_menu_link_update($link) {
  $tid = _taxonomy_menu_get_tid($link['mlid']);
  if ($tid) {
    $term = taxonomy_term_load($tid);
    if ($link['hidden'] == 1 || $term->name != $link['link_title']) {
      db_merge('taxonomy_menu_extras')
        ->key(array('tid' => $tid))
        ->fields(array(
            'hidden' => $link['hidden'],
            'link_title' => $link['link_title'],
        ))
        ->execute();
    }
    else {
      db_delete('taxonomy_menu_extras')
        ->condition('tid', $tid)
        ->execute();
    }
  }
  else {
    db_delete('taxonomy_menu_extras_parent')
      ->condition('mlid', $link['mlid'])
      ->execute();
    $tid = _taxonomy_menu_get_tid($link["plid"]);
    if ($tid) {
      db_merge('taxonomy_menu_extras_parent')
        ->key(array(
          'mlid' => $link['mlid'],
          'tid' => $tid,
        ))
        ->execute();
    }
  }
}

/**
 * Implements hook_menu_link_update().
 */
function taxonomy_menu_extras_menu_link_delete($link) {
  // Delete the record from our table.
  db_delete('taxonomy_menu_extras_parent')
    ->condition('mlid', $link['mlid'])
    ->execute();
}

/**
 * Implements hook_taxonomy_menu_insert().
 */
function taxonomy_menu_extras_taxonomy_menu_insert(&$item) {
  $taxonomy_menu_extra = db_select('taxonomy_menu_extras', 't')
    ->fields('t')
    ->condition('tid', $item['tid'])
    ->execute()
    ->fetchAssoc();
  if (!empty($taxonomy_menu_extra)) {
    $item['remove'] = $taxonomy_menu_extra['hidden'];
    $item['name'] = $taxonomy_menu_extra['link_title'];
  }
}

/**
 * Implements hook_taxonomy_menu_update().
 */
function taxonomy_menu_extras_taxonomy_menu_update(&$item) {
  $taxonomy_menu_extra = db_select('taxonomy_menu_extras', 't')
    ->fields('t')
    ->condition('tid', $item['tid'])
    ->execute()
    ->fetchAssoc();

  if (!empty($taxonomy_menu_extra)) {
    if (!empty($item['term']->original) && $item['term']->original->name != $item['term']->name) {
        db_merge('taxonomy_menu_extras')
          ->key(array('tid' => $item['term']->tid))
          ->fields(array(
              'link_title' => $item['name'],
          ))
          ->execute();
        $taxonomy_menu_extra['link_title'] = $item['name'];
    }

    $item['remove'] = $taxonomy_menu_extra['hidden'];
    $item['name'] = $taxonomy_menu_extra['link_title'];
  }
}

/**
 * Implements hook_taxonomy_menu_delete().
 */
function taxonomy_menu_extras_taxonomy_menu_delete(&$item) {
  db_delete('taxonomy_menu_extras')
    ->condition('tid', $item['tid'])
    ->execute();
  db_delete('taxonomy_menu_extras_parent')
    ->condition('tid', $item['tid'])
    ->execute();
}

/**
 * Alternative batch finish for taxonomy_menu menu rebuild that adds any custom
 * menu to the parent.
 */
function taxonomy_menu_extras_taxonomy_menu_insert_link_items_success() {
  _taxonomy_menu_insert_link_items_success();
  $result = db_select('taxonomy_menu_extras_parent', 't')
    ->fields('t')
    ->execute();

  foreach ($result as $parent) {
    $parent_mlid = db_query('SELECT mlid FROM {taxonomy_menu} WHERE tid = :tid', array(':tid' => $parent->tid))->fetchField();
    $link = menu_link_load($parent->mlid);
    $link['plid'] = $parent_mlid;
    menu_link_save($link);
  }
}

/**
 * Implements hook_batch_alter().
 */
function taxonomy_menu_extras_batch_alter(&$batch) {
  if (!empty($batch['sets'][0]['finished']) && $batch['sets'][0]['finished'] == '_taxonomy_menu_insert_link_items_success') {
    $batch['sets'][0]['finished'] = 'taxonomy_menu_extras_taxonomy_menu_insert_link_items_success';
  }
}
