<?php
/**
 * @file
 * Code for the contact_form feature.
 */


include_once 'feature_wysiwyg_editor.features.inc';

// Load the skin specific functionality.
module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.skins');

// Load the media module specific functionality.
module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.media');

// Load the text filter specific functionality.
module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.filter');

// Load the wysiwyg settings specific functionality.
module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.settings');

// Load the imce specific functionality.
module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.imce');

// Test menu item
//module_load_include('inc','feature_wysiwyg_editor','includes/feature_wysiwyg_editor.test');

/**
 * Implements hook_init().
 */
function feature_wysiwyg_editor_init() {
  // @todo this should only really load when there is a wysiwyg editor on the page.
  drupal_add_css(drupal_get_path('module', 'feature_wysiwyg_editor') . '/css/wysiwyg.css');
}




