<?php

/**
 * Implements hook_init().
 */
function info_plugins_init() {
  // Including all the plugin type files that are enabled for the site.
  info_plugins_include_plugin_types();
}

/**
 * Implements hook_menu().
 */
function info_plugins_menu() {
  $items = array();

  $items['admin/config/info-plugins'] = array(
    'title' => t('Administer Info Plugins'),
    'description' => t('Specify which types of plugins do you want to enable.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('info_plugins_admin_form'),
    'access arguments' => array('administer info plugin types'),
    'file' => 'includes/admin.inc'
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function info_plugins_permission() {
  return array('administer info plugin types' => array(
    'title' => t('Administer Info Plugin Types'),
    'description' => t('Enabled/disable the exposed info plugin types.')
  ));
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function info_plugins_ctools_plugin_directory($module, $plugin) {
  if ($module == 'info_plugins' && in_array($plugin, array_keys(info_plugins_ctools_plugin_type())) ) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function info_plugins_ctools_plugin_type() {
  info_plugins_include('helpers');
  return info_plugins_get_enabled_plugin_types();
}

/**
 * Includes files from the module.
 *
 * @param $name
 * @param string $subfolder
 * @return bool|string
 */
function info_plugins_include($name, $subfolder = NULL) {
  if ($subfolder) {
    return module_load_include('inc', 'info_plugins', $subfolder . '/' . $name);
  }

  $included = module_load_include('inc', 'info_plugins', $name);
  if ($included) {
    return;
  }

  return module_load_include('inc', 'info_plugins', 'includes/' . $name);
}

/**
 * Includes all the enabled plugin_types defined by this module.
 */
function info_plugins_include_plugin_types() {
  $enabled = variable_get('info_plugins_enabled_types', array());
  foreach ($enabled as $name) {
    require_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'info_plugins') . '/plugin_types/' . $name . '.inc';
  }
}

/**
 * Implements hook_modules_disabled().
 */
function info_plugins_modules_disabled($modules) {
  // Disable all the plugin types for disabled modules.
  $contrib = variable_get('info_plugins_contrib_types', array());
  $enabled = variable_get('info_plugins_enabled_types', array());

  if (!$contrib) {
    return;
  }

  foreach ($contrib as $module => &$types) {
    if (!in_array($module, $modules)) {
      continue;
    }

    foreach ($types as $type) {
      if (isset($enabled[$type])) {
        unset($enabled[$type]);
      }
    }

    unset($contrib[$module]);
  }

  variable_set('info_plugins_enabled_types', $enabled);
  variable_set('info_plugins_contrib_types', $contrib);
}