<?php
// $Id$

/**
 * @file
 * Install script to install the om_subthemer module
 *
 * @author: Daniel Honrade http://drupal.org/user/351112
 * 
 */

/**
 * Implementation of hook_install().
 */

function om_subthemer_install() {

  // Use schema API to create database table.
  drupal_install_schema('om_subthemer');

  /**
   * sample format if default contents are to be included
   db_query("INSERT INTO {om_subthemer_vars} (variable, value_html, value_php, source, type) 
             VALUES ('Identity', '<div ... </div>', '<?php print  theme(...); ?>', 'OM', 'subtheme')");
  */           
}


/**
 * Implementation of hook_uninstall().
 */
function om_subthemer_uninstall() {
  // Use schema API to delete database table.
  drupal_uninstall_schema('om_subthemer');
  
  // deleting all om_subthemer_*
  $sql = "SELECT * FROM {variable} 
          WHERE name LIKE :om";
  
  $result = db_query($sql, array(':om' => 'om_subthemer_%'));
  
  while ($record = $result->fetchObject()) {
    variable_del($record->name);
  }
}


/**
 * Implementation of hook_schema().
 */
function om_subthemer_schema() {

$schema['om_subthemer'] = array(
  'description' => t('OM Subthemer Skin to Node relationship'),
  'fields' => array(
    'nid' => array(
      'description' => t('Node ID'),
      'type' => 'int',
      'not null' => TRUE,
    ),
    'skin' => array(
      'description' => t('OM Subthemer Skin'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'regions' => array(
      'description' => t('Subtheme Regions'),
      'type' => 'text',
      'not null' => FALSE,
    ),    
  ),
);

$schema['om_subthemer_layout'] = array(
  'description' => t('OM Subthemer Layout'),
  'fields' => array(
    'lid' => array(
      'description' => t('Layout ID'),
      'type' => 'serial',
      'not null' => TRUE,
    ),
    'cid' => array(
      'description' => t('Child ID'),
      'type' => 'int',
      'not null' => TRUE,
    ),
    'pid' => array(
      'description' => t('Parent ID'),
      'type' => 'int',
      'not null' => TRUE,
    ),
    'tagid' => array(
      'description' => t('Tag Names'),
      'type' => 'varchar',
      'length' => '30',
      'not null' => TRUE,
    ),
    'type' => array(
      'description' => t('Column/Row/Variable'),
      'type' => 'varchar',
      'length' => '10',
      'not null' => TRUE,
    ),
    'iw' => array(
      'description' => t('Inner Wrapper'),
      'type' => 'int',
      'size' => 'tiny',
      'not null' => TRUE,
    ),
    'weight' => array(
      'description' => t('Weight'),
      'type' => 'int',
      'not null' => TRUE,
      'default' => 0,
    ),
    'nid' => array(
      'description' => t('Node ID'),
      'type' => 'int',
      'not null' => TRUE,
    ),
  ),
  'primary key' => array('lid'),
);

$schema['om_subthemer_vars'] = array(
  'description' => t('All theme variables, both html and php'),
  'fields' => array(
    'vid' => array(
      'description' => t('Variable ID'),
      'type' => 'serial',
      'not null' => TRUE,
    ),
    'variable' => array(
      'description' => t('Variable Name'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'value_html' => array(
      'description' => t('HTML Value'),
      'type' => 'text',
      'not null' => TRUE,
    ),
    'value_php' => array(
      'description' => t('PHP Value'),
      'type' => 'text',
      'not null' => TRUE,
    ),
    'source' => array(
      'description' => t('Source, Drupal, Theme Name'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'type' => array(
      'description' => t('Content Type'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
  ),
  'primary key' => array('vid'),
);

$schema['om_subthemer_blocks'] = array(
  'description' => t('This table holds dummy blocks'),
  'fields' => array(
    'bid' => array(
      'description' => t('Block ID'),
      'type' => 'serial',
      'not null' => TRUE,
    ),
    'title' => array(
      'description' => t('Block Description Title'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'content' => array(
      'description' => t('Block Content'),
      'type' => 'text',
      'not null' => TRUE,
    ),
    'module' => array(
      'description' => t('Block Module'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'region' => array(
      'description' => t('Block Region'),
      'type' => 'varchar',
      'length' => '20',
      'not null' => TRUE,
    ),
    'weight' => array(
      'description' => t('Block Weight'),
      'type' => 'int',
      'not null' => TRUE,
    ),
    'nid' => array(
      'description' => t('Node ID'),
      'type' => 'int',
      'not null' => TRUE,
    ),
  ),
  'primary key' => array('bid'),
);
  return $schema;
}


