<?php

/**
 * @file
 * The easiers way to have the admin menu responsive.
 */

/**
 * Implements hook_page_build().
 */
function admin_menu_navbar_page_build(&$page) {

  $detect = mobile_detect_get_object();
  $is_mobile = $detect->isMobile();

  if (!$is_mobile) {
    drupal_add_css(drupal_get_path('module', 'admin_menu_navbar') . '/css/admin_menu_navbar_desktop.css');
  }

  if ($is_mobile) {
    drupal_add_css(drupal_get_path('module', 'admin_menu_navbar') . '/css/admin_menu_navbar_mobile.css');
  }
}

/**
 * Implements hook_help().
 */
function admin_menu_navbar_help($path, $arg) {
  switch ($path) {
    case 'admin/help#admin_menu_navbar':
      $output = '';
      $output .= '<h3>' . t('Introduction') . '</h3>';
      $output .= '<p>' . t('This module would allow you to combine the Drupal Mobile Friendly Navigation Toolbar Menu whenever the users are at their mobile devices and the administration menu when the user at large screen.') . '</p>';
      return $output;
  }
}
