<?php

/**
 * Implements hook_modules_enabled().
 */
function cinc_sync_modules_enabled($modules) {
  cinc_sync_check_for_info_lines($modules);
}

/**
 * Checks modules for .info references to cinc_sync.
 */
function cinc_sync_check_for_info_lines($modules) {

  $paths = array();

  foreach ($modules as $module) {
    $info = drupal_parse_info_file(drupal_get_path('module', $module) . '/' . $module . '.info');
    if (isset($info['cinc_sync'])) {
      if (is_array($info['cinc_sync'])) {
        foreach ($info['cinc_sync'] as $path) {
          $paths[] = $path;
        }
      }
      else {
        $paths[] = $info['cinc_sync'];
      }
    }
  }

  if (count($paths) > 0) {
    cinc_sync_parse_paths($paths, variable_get('cinc_sync_source', 'http://cinc.io/project'));
  }

}

/**
 * Parses remote paths for YAML files.
 */
function cinc_sync_parse_paths($paths, $source) {
  $yaml_files = array();
  foreach ($paths as $path) {
    $url = $source . '/' . $path . '.json';
    $result = drupal_http_request($url);
    if ($result->code == '200') {
      try {
        $data = json_decode($result->data);
      }
      // TOODO: Track JSON errors.
      catch (Exception $e) {}

      if (isset($data->yaml)) {
        $yaml_data = (array) $data->yaml;
        foreach ($yaml_data as $file => $yaml) {
          $uri = $source . '/' . $path . '/' . $file;
          $yaml_file = array(
            'yaml' => cinc_yaml_from_yaml($yaml),
            'file' => new StdClass,
          );
          $yaml_file['file']->uri = $uri;
          $yaml_file['file']->filename = $file;
          $name = explode('.', $file);
          array_pop($name);
          $yaml_file['file']->name = implode('.', $name);
          $yaml_files[$uri] = $yaml_file;
        }
      }
    }
    // TOODO: Track HTTP errors.
    else {}
  }
  cinc_yaml_apply_yaml_files($yaml_files);
  if (function_exists('drush_log') && count($yaml_files)) {
    drush_log(t('Applied CINC Sync configuration from @count.', array(
      '@count' => format_plural(count($yaml_files), '1 file', '@count files')
    )), 'ok');
  }
}
