<?php

/**
 * @file
 * Install file for NYS Global Navigation module.
 */

/**
 * Implements hook_requirements().
 */
function nys_global_nav_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $t = get_t();
    $library = libraries_detect('nys_global_nav');
    $error_type = isset($library['error']) ? drupal_ucfirst($library['error']) : '';
    $error_message = isset($library['error message']) ? $library['error message'] : '';

    if (empty($library['installed'])) {
      $requirements['nys_global_nav_library'] = array(
        'title' => $t('Global Navigation library'),
        'value' => $t('@e: At least @a', array('@e' => $error_type, '@a' => NYS_GLOBAL_NAV_MIN_PLUGIN_VERSION)),
        'severity' => REQUIREMENT_ERROR,
        'description' => $t('!error You need to download the !nys_global_nav, extract the archive, rename the directory to nys_global_nav and place the nys_global_nav directory in the %path directory on your server.', array('!error' => $error_message, '!nys_global_nav' => l($t('Global Navigation library'), $library['download url']), '%path' => 'sites/all/libraries')),
      );
    }
    elseif (version_compare($library['version'], NYS_GLOBAL_NAV_MIN_PLUGIN_VERSION, '>=')) {
      $requirements['nys_global_nav_library'] = array(
        'title' => $t('Global Navigation library'),
        'severity' => REQUIREMENT_OK,
        'value' => $library['version'],
      );
    }
    else {
      $requirements['nys_global_nav_library'] = array(
        'title' => $t('Global Navigation library'),
        'value' => $t('At least @a', array('@a' => NYS_GLOBAL_NAV_MIN_PLUGIN_VERSION)),
        'severity' => REQUIREMENT_ERROR,
        'description' => $t('You have version @version of the Global Navigation library.  You need to download a later version of the !nys_global_nav and replace the old version located in the %path directory on your server.', array('!nys_global_nav' => l($t('Global Navigation library'), $library['download url']), '%path' => $library['library path'], '@version' => $library['version'])),
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_install().
 *
 * Add 2 Drupal variables, nys_global_nav_header_auto &
 *   nys_global_nav_footer_auto, and default to TRUE.
 * Set module weight to be 2nd highest so module's hook_page_build runs last.
 */
function nys_global_nav_install() {
  // Add the variables and set it TRUE.
  variable_set('nys_global_nav_header_auto', TRUE);
  variable_set('nys_global_nav_footer_auto', TRUE);
  // Find the maximum module weight of enabled modules.
  if (module_exists('nys_unav')) {
    // If uNav is enabled, assume it is highest weight module,
    // but get second highest (uNav sets itself to +10).
    $max_weight = db_query('SELECT weight FROM {system} WHERE name = :name', array(':name' => 'nys_unav'))->fetchField() - 10;
  }
  else {
    // Otherwise find maximum weight.
    $max_weight = db_query('SELECT MAX(weight) FROM {system} WHERE status = :status', array(':status' => 1))->fetchField();
  }

  // Set our module to 5 heavier, so ours moves lower in execution order.
  db_update('system')
    ->fields(array('weight' => $max_weight + 5))
    ->condition('name', 'nys_global_nav', '=')
    ->condition('type', 'module', '=')
    ->execute();

  $library = libraries_detect('nys_global_nav');
  $t = get_t();
  drupal_set_message($t('NYS Global Navigation installed.  Make sure you download the !nys_global_nav, extract the archive, rename the directory to nys_global_nav and place the nys_global_nav directory in the %path directory on your server.', array('!nys_global_nav' => l($t('Global Navigation library'), $library['download url']), '%path' => 'sites/all/libraries')));
}

/**
 * Implements hook_uninstall().
 */
function nys_global_nav_uninstall() {
  // Delete the variables to clean up.
  variable_del('nys_global_nav_agency_name');
  variable_del('nys_global_nav_agency_color');
  variable_del('nys_global_nav_header_auto');
  variable_del('nys_global_nav_header_menu');
  variable_del('nys_global_nav_footer_auto');
  variable_del('nys_global_nav_footer_menu');
  // Delete the social media variables too.
  if (!function_exists('_nys_global_nav_setup_social_names')) {
    include_once 'nys_global_nav.module';
  }
  $social = _nys_global_nav_setup_social_names();
  foreach ($social as $key => $value) {
    $social_media_index_name = 'nys_global_nav_social_media_' . check_plain($key);
    variable_del($social_media_index_name);
  }
}
