services:
  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_administrators.php
  cm.administrators:
    arguments: ['@cm.auth']
    class: CS_REST_Administrators
    file: '%campaignmonitor/csrest_administrators.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_campaigns.php
  cm.campaigns:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Campaigns
    file: '%campaignmonitor/csrest_campaigns.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_clients.php
  cm.clients:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Clients
    file: '%campaignmonitor/csrest_clients.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_general.php
  cm.general:
    arguments: ['@cm.auth']
    class: CS_REST_General
    file: '%campaignmonitor/csrest_general.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_lists.php
  cm.lists:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Lists
    file: '%campaignmonitor/csrest_lists.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_people.php
  cm.people:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_People
    file: '%campaignmonitor/csrest_people.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_segments.php
  cm.segments:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Segments
    file: '%campaignmonitor/csrest_segments.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_subscribers.php
  cm.subscribers:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Subscribers
    file: '%campaignmonitor/csrest_subscribers.php'

  # https://github.com/campaignmonitor/createsend-php/blob/master/csrest_templates.php
  cm.templates:
    arguments: ['@cm.null', '@cm.auth']
    class: CS_REST_Templates
    file: '%campaignmonitor/csrest_templates.php'
