<?php
/**
 * @file
 * Install and uninstall functions for the opac items module.
 */

/**
 * Implements hook_schema().
 */
function opac_items_schema() {
  $schema['opac_items_mapping'] = array(
    'description' => 'Stores items fields we want to be displayed.',
    'fields' => array(
      'serv_id' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
      ),
      'item_field' => array(
        'type' => 'varchar',
        'not null' => TRUE,
        'length' => 32,
      ),
      'display_header' => array(
        'type' => 'varchar',
        'not null' => TRUE,
        'length' => 255,
      ),
      'vid' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'null' => TRUE,
      ),
      'vocabulary_machine_name' => array(
        'type' => 'varchar',
        'null' => TRUE,
        'length' => 255,
      ),
      'vocabulary_name' => array(
        'type' => 'varchar',
        'null' => TRUE,
        'length' => 255,
      ),
      'term_field' => array(
        'type' => 'varchar',
        'null' => TRUE,
        'length' => 255,
      ),
      'term_field_label' => array(
        'type' => 'varchar',
        'null' => TRUE,
        'length' => 255,
      ),
      'nomatch_rule' => array(
        'type' => 'varchar',
        'null' => TRUE,
        'length' => 255,
      ),
      'show_as_link' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
      ),
      'weight' => array(
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'foreign keys' => array(
      'opac_servers_serv_id' => array(
        'table' => 'opac_servers', 'columns' => array('serv_id' => 'serv_id'),
      ),
    ),
    'primary key' => array('serv_id', 'item_field'),
  );

  return $schema;
}

/**
 * Remove vid column from opac_items_mapping table.
 */
function opac_items_update_7100(&$sandbox) {
  $description = t('Remove vid column from opac_items_mapping table.');
  db_drop_field('opac_items_mapping', 'vid');
  return $description;
}

/**
 * Add 'show_as_link' column in opac_items_mapping table.
 */
function opac_items_update_7200(&$sandbox) {
  db_add_field(
    'opac_items_mapping',
    'show_as_link',
    array(
      'type' => 'int',
      'not null' => TRUE,
      'default' => 0,
      'size' => 'tiny',
    )
  );

  return "show_as_link column successfully added.";
}
