<?php

/**
 * Implements hook_install()
 * Adds the module-wide variables to the database
**/
function kcfinder_install() {
  variable_set('kcfinder_library_path', kcfinder_find_library_path()); // KCFinder library relative path to drupal root
  variable_set('kcfinder_upload_url', url('sites/default/files/kcfinder', array('absolute' => TRUE, 'language' => FALSE))); // Upload folder absolute URL (no trailing slash)
  variable_set('kcfinder_upload_dir', ''); // Upload directory server absolute route
  variable_set('kcfinder_theme', 'oxygen'); // Name of the theme to use
}


/**
 * Implements hook_requirements().
 */
function kcfinder_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $t = get_t();
    
	if(!kcfinder_library_exists()) {
		$requirements['kcfinder'] = array(
		  'title' => $t('KCFinder web file manager'),
		  'value' => $t('Not present'),
		  'severity' => REQUIREMENT_ERROR,
		  'description' => $t('To use the KCFinder integration module, you need to download and extract the !kcfinder_lib_link in the library folder of your site (example: "example.com/sites/all/libraries"). For more information, please refer to the !kcfinder_mod_link.',
			array(
			  '!kcfinder_lib_link' => l(t('KCFinder web file manager'), 'http://kcfinder.sunhater.com'),
			  '!kcfinder_mod_link' => l(t('installation instructions'), 'http://drupal.org/project/kcfinder')
			))
		);
	}
	else {
	  $requirements['kcfinder'] = array(
        'title' => $t('KCFinder web file manager'),
        'severity' => REQUIREMENT_OK,
        'value' => $t('Present')
      );
	}
  }

  return $requirements;
}


/**
 * Implements hook_uninstall().
 */
function kcfinder_uninstall() {
  variable_del('kcfinder_library_path');
  variable_del('kcfinder_upload_url');
  variable_del('kcfinder_upload_dir');
  variable_del('kcfinder_theme');
}


/**
 * Update 7001: Delete unused variables from previous versions.
 */
function kcfinder_update_7001() {
  $ret = array();
  variable_del('kcfinder_alt_path');
  return $ret;
}