language: php

php:
  - 5.4
  - 5.5

cache:
  apt: true
  directories:
    - vendor

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update > /dev/null

install:

  # Update composer
  - composer selfupdate
  - composer install

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Install global composer dependencies.
  - composer global require --prefer-dist --no-interaction drush/drush:6.* phing/phing:2.7.* squizlabs/php_codesniffer:1.5.* youngj/httpserver:dev-master#aabdd56e2be82c12c313b236cee94da1fa3401a2
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Disable sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Set phing properties
  - cp build.travis.properties build.properties

  - phpenv rehash

before_script:

  # Validate source code.
  - phing validate

  # Prepare a previous version for upgrade (optional)
  - phing prepare

  # Install the site.
  - phing install

  # Start the server.
  - cd ../accessible_forms-build && drush runserver 8888 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done

script:

  - phing test

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID
