<?php

/**
 * @file 
 * Install, update and uninstall functions for the clock module.
 */

/**
 * Implements hook_uninstall().
 */
function clock_uninstall() {
  // Delete all clock variables.
  variable_del('clock_time_zone');
  variable_del('clock_date_type');
  variable_del('clock_update');
}

/**
 * Remove legacy variables from the database.
 */
function clock_update_7100(&$sandbox) {
  variable_del('clock_timezone_type');
  variable_del('clock_custom_timezone');
  variable_del('clock_date_format_type');
  variable_del('clock_custom_date_format');
  variable_del('clock_js');
  return 'Legacy variables removed.';
}
