<?php

/**
 * hook_module_plugin()
 *
 * Automatically created by CTools for every plugin defined.
 *
 * Two plugins will be defined here.
 * 1) commerce kickstart content types.
 * 2) regular content types.
 *
 * Using a predefined structure (array format).
 */
function good_relations_products_good_relations_product() {
  $commerce_product_reference_node_types = _products_good_relations_load();
  $content_types_nodes = _products_good_relations_load_regular();

  // Plugin structure respected for the variation types.
  $configured_variation_types = array();
  // Custom array to exclude the variation types from the content types.
  $variation_types_content_format = array();

  foreach ($commerce_product_reference_node_types as $cprnt) {
    $configured_variation_types = array_merge($configured_variation_types, array(
      $cprnt->type => array(
        'label' => $cprnt->name,
        'handler' => array(
          'class' => 'good_relations_content_types',
        ),
      ),
    ));
    $variation_types_content_format = array_merge($variation_types_content_format, array($cprnt->type => $cprnt->name));
  }

  // Exclude variation types from content types => regular content types.
  $unconfigured_regular_content_types = array_diff($content_types_nodes, $variation_types_content_format);
  // Plugin structure respected for the regular content types.
  $configured_regular_content_types = configure_regular_content_types($unconfigured_regular_content_types);

  $configured_variation_types['entity'] = 'node';
  $configured_variation_types['label'] = 'Variation types';
  $configured_regular_content_types['entity'] = 'node';
  $configured_regular_content_types['label'] = 'Regular content types';

  $plugins = array(
    'variation_types' => $configured_variation_types,
    'regular_content_types' => $configured_regular_content_types,
  );

  return $plugins;
}

/**
 * Load all of the variation types defined in the database.
 *
 * @return mixed
 */
function _products_good_relations_load() {
  $result = array();
  if (module_exists('commerce')) {
    $result = commerce_product_reference_node_types();
  }
  return $result;
}

/**
 * Load all of the content types (including variation types).
 *
 * @return mixed
 */
function _products_good_relations_load_regular() {
  return node_type_get_names();
}

/**
 * Configure the structure of the plugin, for regular content types.
 *
 * @param $urct
 * @return array
 */
function configure_regular_content_types($urct) {
  $new_keys = array_keys($urct);
  $new_values = array();
  foreach ($urct as $key => $value) {
    $new_values = array_merge($new_values, array(
      $value => array(
        'label' => $value,
        'handler' => array(
          'class' => 'good_relations_content_types',
        ),
      ),
    ));
  }
  $urct = array_combine($new_keys, $new_values);

  return $urct;
}
