<?php

/**
 * @file
 *  Issue pop integration module functions.
 */

/**
 * Implements hook_block_info().
 */
function issuepop_block_info() {
  $blocks = array();

  $blocks['pager_link'] = array(
    'info' => t('Issue Pop pager link'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function issuepop_block_view($delta) {
  switch($delta) {
    case 'pager_link':
      return issuepop_block_pager_link_view();
    default:
      return t('Invalid delta');
  }
}

function issuepop_block_pager_link_view() {
  $block = array(
    'content' => array(
      // TODO: Make label configurable.
      '#markup' => t('<a href="#" id="issuepop_open">Feedback</a>'),
      '#attached' => array(
        'js' => array(
          array(
            'data' => 'http://cdn.issuepop.com/js/pager_legacy.min.js',
            'type' => 'external',
            'scope' => 'footer',
          ),
        ),
        'library' => array(
          array('system', 'ui.dialog'),
        ),
      ),
    ),
  );

  return $block;
}
