<?php

/**
 * Move background color configuration to the mobi theme.
 */
function mobi_loader_update_6000() {
  variable_del('mobi_loader_header_background_color');
  variable_del('mobi_loader_left_background_color');
  variable_del('mobi_loader_content_background_color');
  variable_del('mobi_loader_right_background_color');
  variable_del('mobi_loader_footer_background_color');
  return array();
}
