<?php


/**
 * Implements hook_menu().
 */
function adroll_menu() {
  $items = array();

  $items['admin/config/system/adroll'] = array(
    'title' => 'Adroll settings',
    'description' => 'Configure the settings used to generate your Adroll tracking code.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('adroll_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'adroll.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_theme().
 */
function adroll_theme() {
  return array(
    'adroll_trackingcode' => array(
      'template' => 'adroll_js',
      'variables' => array(
        'adv_id' => '',
        'pix_id' => '',
      )
    )
  );
}


/**
 * Implements hook_page_build().
 */
function adroll_page_build(&$page) {
  $page['page_bottom']['adroll'] = array(
    '#theme' => 'adroll_trackingcode',
    '#pix_id' => variable_get('adroll_pix_id', FALSE),
    '#adv_id' => variable_get('adroll_adv_id', FALSE),
    '#access' => _adroll_should_track(),
  );
}


/**
 * Decides whether track the user or not.
 *
 * @param $account
 *   A user object containing an array of roles to check
 * @return boolean
 *   A decision on if the current user is being tracked by getClicky
 */
function _adroll_should_track() {
  global $user;

  // Check Adroll is configured
  $adv_id = variable_get('adroll_adv_id', FALSE);
  if (!$adv_id) {
    return FALSE;
  }

  // Check admin page
  $admin_paths = path_get_admin_paths();
  if (drupal_match_path(current_path(), $admin_paths['admin'])) {
    return FALSE;
  }

  // Check user role segmentation
  $allowed_roles = variable_get('adroll_target_roles', array());
  foreach (array_keys($user->roles) as $role) {
    if (isset($allowed_roles[$role])) {
     return TRUE;
    }
  }

  return FALSE;
}
