<?php
/**
 * @file
 * Social network UD install file
 * uninstalls the variables declared.
 */

/**
 * Implements of hook_uninstall().
 */
function social_network_user_detection_uninstall() {
  variable_del('social_network_user_detection_fb_app_id');
  variable_del('social_network_user_detection_mode');
  variable_del('social_network_user_detection_hyves_app_id');
  variable_del('social_network_user_detection_do_not_use_fb_init');
  variable_del('social_network_user_detection_do_not_use_hyves_init');
}
