#!/bin/sh

### BEGIN INIT INFO
# Provides: worker
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Short-Description: worker deamon
# Description: Worker deamon that spawns a worker to perform jobs and monitors the process.
### END INIT INFO

. /etc/rc.status
rc_reset

case "$1" in
  start)
    echo 'Starting worker deamon'
      cd /srv/worker
      drush wdeamon wwwrun < /dev/null > /dev/null 2>&1 &
      rc_status -v
    ;;
  stop)
    echo 'Stopping worker deamon'
    kill `ps -ef | grep 'drush.php wdeamon' | awk '{ print $2 }'` 2> /dev/null
    rc_status -v
  ;;

  *)
    echo "Usage: $0 (start|stop)"
    RETVAL=1
esac

rc_exit
