<?php
/**
 * @file
 * Code for the NS Blog post feature.
 */

include_once('ns_blog_post.features.inc');

/**
 * Implements hook_defaultconfig_optionals().
 */
function ns_blog_post_defaultconfig_optionals() {
  $optionals = array();
  $optionals['field_default_fields']['node-ns_blog_post-field_ns_blog_post_related'] = array(
    'title' => t('Related blog posts'),
    'description' => t('Relate blog posts to other blog posts.'),
    'default' => FALSE,
  );
  $optionals['field_default_fields']['node-ns_blog_post-field_ns_blog_post_lead'] = array(
    'title' => t('Blog post leads'),
    'description' => t('Add lead texts to blog posts.'),
    'default' => FALSE,
  );
  $optionals['field_default_fields']['node-ns_blog_post-field_ns_blog_post_file_attach'] = array(
    'title' => t('Blog post file attachments'),
    'description' => t('Attach files to blog posts.'),
    'default' => FALSE,
  );
  return $optionals;
}
