<?php

/**
 * @file
 * Cultura questionnaire samples are provided on install; see .install file.
 */

/**
 * Utility function to save a node given a node_export-style opbject.
 *
 * This object should be modified from node_export (nid and many other values
 * removed) if taken from node_export but this wrapper accepts this simpler
 * array and works around a node_save() quirk.
 */
function cultura_questionnaire_samples_node_save($node, $author_uid = 1) {
  $node->language = LANGUAGE_NONE;
  node_object_prepare($node);
  // Set the uid that node_object_prepare() loses anyway.
  $node->uid = $author_uid;
  // Pretty sure nothing helps the revision uid, unfortunately...
  $node->revision_uid = $author_uid;
  node_save($node);
  return $node;
}
