<?php
/**
 * @file
 * Schema definitions install/update/uninstall hooks.
 */
 
  /**
  * Implements fo hook_install()
  */
  function yelp_api_install() {
    //na da
  }
 
  /**
   * Implements hook_uninstall()
   */
  function yelp_api_uninstall() {
    drupal_uninstall_schema('yelp_api');
  }
 
  /**
 * Implements hook_schema().
 */
  function yelp_api_schema() {
    $schema  = array();
    $schema['yelp_data'] = array(
      'description'  => t('Table that contains yelp search data settings'),
      'fields'  => array(
        'yelp_id' => array(
          'type'         => 'serial',
          'unsigned'     => TRUE,
          'not null'     => TRUE,
          'description' => 'The primary unique id',
        ),
        'location' => array(
          'type'         => 'text',
          'not null'     => TRUE,
          'description'  => 'the location to search from',
        ),
        'radius' => array(
          'type'         => 'varchar',
          'length'       => 255,
          'not null'     => TRUE,
          'default'      => '1',
          'description'  => 'the radius in miles to search',
        ),
        'max_results' => array(
          'type'         => 'varchar',
          'length'       => 255,
          'not null'     => TRUE,
          'default'      => '20',
          'description'  => 'the max number of results to return per API call',
        ),
        'cc' => array(
          'type'         => 'varchar',
          'length'       => 255,
          'not null'     => TRUE,
          'default'      => 'us',
          'description'  => 'the two letter country to search, two letter code',
        ),
        'lang' => array(
          'type'         => 'varchar',
          'length'       => 255,
          'not null'     => TRUE,
          'default'      => 'en',
          'description'  => 'the language to get results in',
        ),
        'categories' => array(
          'type'         => 'text',
          'not null'     => TRUE,
          'description'  => 'the yelp categories to search',
        ),
      ),
      'primary key' => array('yelp_id'),
      'unique keys' => array(
        'yelp_id' => array('yelp_id'),
      ),
    );
    return $schema;
  }