<?php

/**
 * @file
 * Provides a context condition based on current date.
 */

/**
 * Implements hook_ctools_plugin_api().
 *
 * Make module compatible with context 3.x.
 */
function context_date_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function context_date_context_plugins() {
  $plugins = array();
  $plugins['context_date_condition'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_date'),
      'file' => 'context_date_condition.inc',
      'class' => 'context_date_condition',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_date_context_registry() {
  return array(
    'conditions' => array(
      'context_date' => array(
        'title' => t('Date'),
        'plugin' => 'context_date_condition',
      ),
    ),
  );
}

/**
 * Implements hook_context_page_condition().
 */
function context_date_context_page_condition() {
  if ($plugin = context_get_plugin('condition', 'context_date')) {
    $plugin->execute();
  }
}
