<?php
/**
 * @file
 * Install, update and uninstall functions for the millennium_cck module.
 *
 */


/**
 * Implements hook_install().
 */
function millennium_cck_install() {

}

/**
 * Implements hook_uninstall().
 */
function millennium_cck_uninstall() {
  // Remove variables
  db_delete('variable')
  ->condition('name', 'millennium_cck_mapping_%', 'LIKE')
  ->execute();
  cache_clear_all('variables', 'cache');

}
