---
language: python
python: "2.7"

env:
  - SITE=test.yml

notifications:
  slack:
    secure: "r8SI/zRizx3D8oD7oE+t957V+BiBWxzhZv2e6/Wwea99KTiJWlRWJXXC2HwBTH4nXo2XArGXua7Cv5OW3A+l4PK9AP7hqyzjg+X3OcXjAPqF9cJMuwQJJ5wIvcT+F5G5lFpcLIQE6aFpunS6v2NvO3U5rmyf+RhuEPtOe4a5syQ="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl
  # Avoid harmless (but annoying) warnings.
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs
  # Completely remove mysql
  - sudo pkill -f mysql
  - sudo apt-get remove -y --purge mysql-server mysql-client mysql-common
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo rm -rf /root/.my.cnf

install:
  # Install Ansible from sources.
  - curl https://raw.githubusercontent.com/GetValkyrie/ansible-bootstrap/master/install-ansible.sh|sudo /bin/sh

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Make the repo available unser the published role name
  - cd ..; ln -s ansible-role-valkyrie getvalkyrie.valkyrie; cd -

  # Install required dependencies.
  - ansible-galaxy install geerlingguy.mysql
  - ansible-galaxy install http://github.com/getvalkyrie/ansible-role-aegir,,getvalkyrie.aegir
  - ansible-galaxy install http://github.com/getvalkyrie/ansible-role-skynet,,getvalkyrie.skynet

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check if Aegir is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir
  # Check that Skynet queue is running
  - sudo supervisorctl status skynet-queue | grep uptime
  # Check that Avahi-alaises is running
  - sudo supervisorctl status avahi-aliases | grep uptime
