<?php

/**
 * Implements hook_element_info().
 */
function fapi_table_element_info() {
  return array(
    'fapi_table' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#theme' => array('fapi_table'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function fapi_table_theme() {
  return array(
    'fapi_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Theme callback.
 */
function theme_fapi_table($variables) {
  $element = $variables['element'];
  $element['#theme'] = 'table';
  $element['#rows'] = array();
  foreach (element_children($element) as $child) {
    $row = array();
    if (isset($element[$child]['#attributes'])) {
      $row += $element[$child]['#attributes'];
    }
    foreach (element_children($element[$child]) as $cell) {
      $row['data'][] = drupal_render($element[$child][$cell]);
    }
    $element['#rows'][] = $row;
  }
  return drupal_render($element);
}
