<?php

/**
 * @file
 * integrates mail_ru module into OpenID Selector module.
 * See http://www.gerixsoft.com/blog/drupal/openid-selector-twitter
 *
 * @author: Andriy Gerasika <www.gerixsoft.com/contact>
 */

/**
 * Implements hook_form_alter().
 *
 * Adds mail.ru to the OpenID (Selector) forms.
 */
function openid_selector_mailru_form_alter(&$form, $form_state, $form_id) {
  $forms = array(
    'user_login_block' => 'user-login-form',
    'user_login' => 'user-login',
  );
  if (array_key_exists($form_id, $forms)) {
    $module_path = drupal_get_path('module', 'openid_selector_mailru');
    drupal_add_js($module_path . '/openid_selector_mailru.js');
  }
}
