<?php

/**
 * @file
 * Exports Drupal Commerce entities via Rules and Drupal's template system.
 */

/**
 * Implements hook_rules_file_info().
 *
 * @todo Remove this function when https://drupal.org/node/2153305 is fixed.
 */
function commerce_export_rules_file_info() {
  return array('commerce_export.rules');
}

/**
 * Implements hook_theme().
 */
function commerce_export_theme($existing, $type, $theme, $path) {
  return array(
    'commerce_export_orders' => array(
      'variables' => array('orders' => NULL),
      'path' => $path . '/templates',
      'template' => 'commerce-export-orders',
      'pattern' => 'commerce-export-orders__',
    ),
  );
}
