name = Drush Make File Entity
description = Defines a file entity for Drush Make files
core = 7.x
package = Other
project = makefile
dependencies[] = ctools
dependencies[] = features
dependencies[] = file_entity
dependencies[] = number
dependencies[] = safeword
dependencies[] = text
features[ctools][] = file_entity:file_type:1
features[features_api][] = api:2
features[field_base][] = field_drush_api_version
features[field_base][] = field_drush_core_api_version
features[field_base][] = field_drush_make_name
features[field_instance][] = file-drush_make-field_drush_api_version
features[field_instance][] = file-drush_make-field_drush_core_api_version
features[field_instance][] = file-drush_make-field_drush_make_name
features[file_type][] = drush_make
project status url = https://updates.dropfort.com/fserver/release-history

; Information added by Drupal.org packaging script on 2014-05-27
version = "7.x-1.x-dev"
core = "7.x"
project = "makefile"
datestamp = "1401212029"

