<?php

/**
 * @file
 * Tests for Drush Make file entity
 */

class MakeFileTestCase extends DrupalWebTestCase {
  public static function getInfo() {
    return array(
      'name' => t('Make File Entity tests'),
      'description' => t('Test the Drush make file entity and parser.'),
      'group' => t('Drush'),
    );
  }

  function setUp() {
    parent::setUp('makefile');
  }

  function testMakeFileParser() {
    
  }
}
