<?php
/**
 * @file
 * Add ACE Editor to Devel Execute PHP forms.
 */

/**
 * Implements hook_libraries_info().
 */
function devel_php_ace_libraries_info() {
  $libraries['ace'] = array(
    'title' => 'Ace Editor',
    'vendor url' => 'http://ace.c9.io/',
    'download url' => 'https://github.com/ajaxorg/ace-builds/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.+\d+.+\d+)"/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'src/ace.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_form_alter().
 */
function devel_php_ace_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'devel_execute_block_form':
    case 'devel_execute_form':
      $form['execute']['code']['#attached']['libraries_load'][] = array('ace');
      $form['execute']['code']['#attached']['js'][] = drupal_get_path('module', 'devel_php_ace') . '/js/devel_php_ace.js';
      $form['execute']['code']['#attached']['css'][] = drupal_get_path('module', 'devel_php_ace') . '/css/devel_php_ace.css';
      $form['execute']['code']['#attributes']['class'][] = 'ace-enabled';
      break;
  }
}
