<?php

/**
 * Implementation of hook_install()
 */
function flag_solved_install() {
  // Set the module weight so it can override advanced_forum modules.
  db_query("UPDATE {system} SET weight = 99 WHERE name = 'flag_solved'");
}

/**
 * Implementation of hook_uninstall()
 */
function flag_solved_uninstall() {
  $aids = variable_get('flag_solved_flag_actions', array());
  foreach ($aids as $aid) {
    flag_actions_delete_action($aid);
  }
  variable_del('flag_solved_flag_actions');
}
