<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oauth"
    nsURI="http://oauth/1.0" nsPrefix="oauth">
  <eClassifiers xsi:type="ecore:EClass" name="OAuth Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="base"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orig_type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OAuth">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oid"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//OAuth%20Type"/>
  </eClassifiers>
</ecore:EPackage>
