/**
 * To login sqlplus:
 *   sqlplus SYS@AL32UTF8/CHANGE AS SYSDBA @drupal_web_test_case.oci.sql
 */

-- Connect with SYS and create new user "test".
CONNECT SYS@AL32UTF8/CHANGE AS SYSDBA

DROP USER test CASCADE;

CREATE USER test PROFILE "DEFAULT" IDENTIFIED BY "CHANGE" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;
GRANT "AQ_ADMINISTRATOR_ROLE" TO test;
GRANT "AQ_USER_ROLE" TO test;
GRANT "AUTHENTICATEDUSER" TO test;
GRANT "CONNECT" TO test;
GRANT "CTXAPP" TO test;
GRANT "DBA" TO test;
GRANT "DELETE_CATALOG_ROLE" TO test;
GRANT "EJBCLIENT" TO test;
GRANT "EXECUTE_CATALOG_ROLE" TO test;
GRANT "EXP_FULL_DATABASE" TO test;
GRANT "GATHER_SYSTEM_STATISTICS" TO test;

-- Connect as user "test".
CONNECT test@AL32UTF8/CHANGE

EXIT;
