<?php
/**
 * @file
 * adds a formatter for text fields that obfuscates the value using ROT13.
 *
 */

/**
 * Implements hook_field_formatter_info().
 *
 * Expose Field API formatter types.
 */
function field_formatter_obfuscate_field_formatter_info() {
  return array(
    'obfuscate_formatter' => array(
      'label' => t('Obfuscate'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Build a renderable array for a field value.
 */
function field_formatter_obfuscate_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  foreach ($items as $delta => &$item) {
    $item['safe_value'] = '<div data-rot13="' . str_rot13($item['safe_value']) . '"></div>';
  }

  $element = text_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, array('type' => 'text_default'));

  return $element;
}
