" ref.: https://github.com/tpope/vim-pathogen
call pathogen#infect()
syntax on
filetype plugin indent on

" ref.: https://github.com/altercation/vim-colors-solarized
syntax enable
set background=dark
colorscheme solarized
