### restmini_service_example url patterns ###

---

# base-route
restmini_service_example:
  # service
  example:
    # endpoint
    hello:
      resource_name: restmini_service_example__example__hello
      description: |
        Basic non-confidential hello.
      base:
        path: /service/restmini-example/example/hello
        regex: ^\/service\/restmini\-example\/hello(\/|\.json)?$
        headers:
          - X-Rest-Service-Response-Info-Wrapper
      known_clients:
        external:
          - Somebody
        internal: null
      methods:
        # method
        GET:
          # operation
          index:
            operation_name: restmini_service_example__example__hello__index
            access_sensitivity: No restriction.
            parameters:
              path: null
              get: null
              post: null
            examples:
              - /service/restmini-example/example/hello
            regex: ^\/service\/restmini\-example\/hello(\/|\.json)?$
    # endpoint
    thingie:
      resource_name: restmini_service_example__example__thingie
      description: |
        Basic non-confidential thingie.
      base:
        path: /service/restmini-example/example/thingie
        regex: ^\/service\/restmini\-example\/thingie(\/|\.json)?$
        headers:
          - X-Rest-Service-Response-Info-Wrapper
      known_clients:
        external:
          - Somebody
        internal: null
      methods:
        # method
        GET:
          # operation
          index:
            operation_name: restmini_service_example__example__thingie__index
            access_sensitivity: No restriction.
            parameters:
              path: null
              get: null
              post: null
            examples:
              - /service/restmini-example/example/thingie
            regex: ^\/service\/restmini\-example\/thingie(\/|\.json)?$
          # operation
          retrieve:
            operation_name: restmini_service_example__example__thingie__retrieve
            access_sensitivity: No restriction.
            parameters:
              path:
                id: integer
              get: null
              post: null
            examples:
              - /service/restmini-example/example/thingie/13
            regex: ^\/service\/restmini\-example\/thingie/[1-9]\d*(\/|\.json)?$
        # method
        POST:
          # operation
          create:
            operation_name: restmini_service_example__example__thingie__create
            access_sensitivity: No restriction.
            parameters:
              path: null
              get: null
              post:
                name: string
                color: string
            examples:
              - /service/restmini-example/example/thingie
            regex: ^\/service\/restmini\-example\/thingie(\/|\.json)?$
        # method
        PUT:
          # operation
          update:
            operation_name: restmini_service_example__example__thingie__update
            access_sensitivity: No restriction.
            parameters:
              path:
                id: integer
              get: null
              post:
                name: string
                color: string
            examples:
              - /service/restmini-example/example/thingie/13
            regex: ^\/service\/restmini\-example\/thingie/[1-9]\d*(\/|\.json)?$
        # method
        DELETE:
          # operation
          delete:
            operation_name: restmini_service_example__example__thingie__delete
            access_sensitivity: No restriction.
            parameters:
              path:
                id: integer|string
              get: null
              post: null
            examples:
              - /service/restmini-example/example/thingie/13
              - /service/restmini-example/example/thingie/*
            regex: ^\/service\/restmini\-example\/thingie/(\*|[1-9]\d*)(\/|\.json)?$
