<?php
/**
 * @file
 * Core functions for the Context variables module.
 */

/**
 * Implements hook_init().
 */
function context_variable_init() {
  $plugin = context_get_plugin('reaction', 'variable');
  if ($plugin) {
    $plugin->execute();
  }
}

/**
 * Implements hook_theme().
 */
function context_variable_theme() {
  $items = array();

  $items['context_variable_form'] = array(
    'render element' => 'form',
  );

  return $items;
}

/**
 * Implements hook_context_plugins().
 */
function context_variable_context_plugins() {
  $plugins = array();

  $plugins['context_reaction_variable'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_variable') . '/plugins',
      'file' => 'context_reaction_variable.inc',
      'class' => 'context_reaction_variable',
      'parent' => 'context_reaction',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_variable_context_registry() {
  $registry = array();

  $registry['reactions'] = array(
    'variable' => array(
      'title' => t('Variables'),
      'description' => t('Set Drupal variables'),
      'plugin' => 'context_reaction_variable',
    ),
  );

  return $registry;
}

/**
 * Theme callback for context options form.
 */
function theme_context_variable_form($variables) {
  $form = $variables['form'];

  drupal_add_css(drupal_get_path('module', 'context_variable') . '/context_variable.css');

  $header = array(t('Varaible settings'), t('Operations'));
  $rows = array();

  // Variables settings form and operations.
  $children = element_children($form['variable']);
  if (!empty($children)) {
    foreach ($children as $variable) {
      $rows[] = array(
        render($form['variable'][$variable]),
        render($form['remove'][$variable]),
      );
    }
  }

  // No variables have been added.
  else {
    $rows[] = array(array(
      'colspan' => 2,
      'data' => t('No variables have been added.'),
    ));
  }

  return theme('table', array(
    'header' => $header,
    'rows' => $rows,
  )) . render($form['add']);
}
