<?php

/**
 * @file
 * Embeds the Nomensa Accessible Media Player within Drupal.
 */

define('NOMENSA_AMP_SETTINGS_FORM', 'admin/config/media/nomensa-amp');

/**
 * Implements hook_menu().
 */
function nomensa_amp_menu() {
  $items[NOMENSA_AMP_SETTINGS_FORM] = array(
    'title' => 'Nomensa Accessible Media Player',
    'description' => 'Administration functions for the Nomensa Accessible Media Player module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nomensa_amp_admin_settings_form'),
    'access arguments' => array('administer nomensa amp'),
    'file' => 'nomensa_amp.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function nomensa_amp_permission() {
  return array(
    'administer nomensa amp' => array(
      'title' => t('Administer the Nomensa Accessible Media Player module.'),
    ),
  );
}

/**
 * Implements hook_init().
 *
 * Loads the files from the Nomensa AMP library.
 */
function nomensa_amp_init() {
  if ($settings = variable_get('nomensa_amp_settings')) {
    if ($library_path = libraries_get_path('nomensa_amp')) {
      // Add the jQuery UI slider.
      drupal_add_library('system', 'ui.slider');

      // Add global CSS and javascript files.
      drupal_add_js($library_path . '/core/javascript/swfobject/swfobject.js');
      drupal_add_js($library_path . '/custom/javascript/jquery.loader.js');

      if (isset($settings['advanced']['minimised']) && $settings['advanced']['minimised'] == 1) {
        // Load the minimised files.
        drupal_add_js($library_path . '/core/javascript/jquery.player.min.js');
        drupal_add_css($library_path . '/core/css/player-core.min.css');
        drupal_add_css($library_path . '/custom/css/player-theme.min.css');
      }
      else {
        // Load the normal files.
        drupal_add_js($library_path . '/core/javascript/jquery.player.js');
        drupal_add_css($library_path . '/core/css/player-core.css');
        drupal_add_css($library_path . '/custom/css/player-theme.css');
      }

      foreach ($settings['players'] as $player => $enabled) {
        // Add player-specific files.
        if ($enabled) {
          switch ($player) {
            case 'vimeo':
              drupal_add_js($library_path . '/custom/javascript/config/vimeo/vimeo.config.js');
              break;

            case 'jwplayer':
              drupal_add_js($library_path . '/custom/javascript/config/jwplayer-5/core/jwplayer.js');
              drupal_add_js($library_path . '/custom/javascript/config/jwplayer-5/jw-player.config.js');
              break;
          }
        }
      }
    }
  }
}