<?php

/**
 * @file
 * This Install file is for Video Bckground.
 */

/**
 * Implements hook_install().
 */
function video_background_install() {
  // Create the video_background directory and ensure it's writable.
  $directory = file_default_scheme() . '://video_background';
  file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS);

  $variables = array(
    'video_background' => array(
      'mp4' => '',
      'webm' => '',
      'ogg' => '',
      'additional' => array(
        'poster' => '',
        'loop' => 1,
        'muted' => 1,
      ),
    ),
  );

  foreach ($variables as $name => $var) {
    variable_set($name, $var);
  }
}

/**
 * Implements hook_uninstall().
 */
function video_background_uninstall() {
  // Remove the video_background directory and uploaded files.
  file_unmanaged_delete_recursive(file_default_scheme() . '://video_background');

  $result = db_query("SELECT fid FROM {file_usage} WHERE module = 'video_background'");

  // Remove all data used files.
  foreach ($result as $record) {
    $file = file_load($record->fid);
    if ($file) {
      // Remove all usage for this file by my_module_name.
      file_usage_delete($file, 'video_background', 'video_background', NULL, 0);
      // Should only delete if file not in use by another module.
      file_delete($file);
    }
  }

  variable_del('video_background');
}
