<?php
/**
 * Installs the project_solr module and enables the project_project
 * content type to be indexed by solr
 */
function project_solr_install() {
  // Reindex all project nodes.
  $env_id = apachesolr_default_environment();
  $bundles = apachesolr_get_index_bundles($env_id, 'node');
  $project_types = project_project_node_types();

  module_load_include('inc','apachesolr', 'apachesolr.index');
  $bundles += $project_types;
  apachesolr_index_set_bundles($env_id,'node', $bundles);

  project_solr_mark_for_reindex();
}

/**
 * Run after project updates so node types exist.
 */
function project_solr_update_dependencies() {
  return array(
    'project_solr' => array(
      7001 => array(
        'project' => 7007,
      ),
    ),
  );
}

/**
 * Implements hook_update_N().
 */
function project_solr_update_7001() {
  // Index keys have changed substantially in Drupal 7,
  // due to project.module's conversion to Field API.
  module_load_include('module', 'project_solr');
  project_solr_mark_for_reindex();
}
