<?php

/**
 * @file
 * Install and update hooks for site_policy module.
 */

/**
 * Implements hook_requirements().
 */
function site_policy_requirements($phase) {
  $requirements = array();
  $t = get_t();

  if ($phase == 'runtime') {
    module_load_include('inc', 'site_policy');

    $user_1_active_time = variable_get('site_policy_user_1_active_time', 0);
    if ($user_1_active_time) {
      $user1 = user_load(1);
      $requirements['site_policy_user_1_enabled'] = array(
        'title' => $t('Site policy: User 1'),
        'value' => !empty($user1->status) ? $t('User 1 is enabled') : $t('User 1 is disabled'),
        'severity' => !empty($user1->status) ? REQUIREMENT_ERROR : REQUIREMENT_OK,
        'description' => $t('User 1 is set to be disabled by cron every %time seconds', array('%time' => $user_1_active_time)),
      );
    }

    $user_1_scramble_pw_interval = variable_get('site_policy_user_1_pw_scramble', 0);
    if ($user_1_scramble_pw_interval) {
      $requirements['site_policy_user_1_pw_scramble'] = array(
        'title' => $t('Site policy: User 1 password'),
        'value' => '',
        'severity' => REQUIREMENT_OK,
        'description' => $t('User 1 password will be scrambled by cron on %date', array('%date' => date('c', _site_policy_get_next_scramble_user_1_password_time()))),
      );
    }
  }

  return $requirements;
}
