<?php

/**
 * @file panel_schedule.module
 * Drupal hooks for panel schedule module.
 */

/**
 * Set up a constant for the ctools API Version number this module supports.
 */
define('PANEL_SCHEDULE_CTOOLS_API_VERSION', 2);


/**
 * Implements hook_ctools_plugin_api().
 *
 * @param $owner
 *   String containing machine name of requesting module.
 * @param $api
 *   String containing machine name of api being used.
 * @return
 *   Array containing the supported API version.
 */
function panel_schedule_ctools_plugin_api($owner, $api) {
  if ($owner == 'ctools' && $api == 'plugins') {
    return array('version' => PANEL_SCHEDULE_CTOOLS_API_VERSION);
  }
}


/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param $owner
 *   String containing machine name of requesting module.
 * @param $plugin_type
 *   String containing machine name of plugin type being requested.
 * @return
 *   String containing path to supported plugin types provided by this module.
 */
function panel_schedule_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return "plugins/$plugin_type";
  }
}