<?php

/**
 * @file
 * Testing functionality for Block API module.
 */

/**
 * Implements hook_bock_api_info().
 */
function block_api_test_block_api_info() {
  $types['html'] = array(
    'title' => t('HTML block'),
    'description' => t('A basic block containing custom HTML code.'),
  );
  return $types;
}

/**
 * Implements hook_bock_api_view().
 */
function block_api_test_block_api_html_view($instance) {
  $block['content'] = check_markup($instance->settings['body']['value'], $instance->settings['body']['format'], '', TRUE);
  return $block;
}

/**
 * Implements hook_bock_api_form().
 */
function block_api_test_block_api_html_form($instance) {
  $form['body'] = array(
    '#type' => 'text_format',
    '#title' => t('Block body'),
    '#description' => t('The content of the block as shown to the user.'),
    '#rows' => 15,
    '#required' => TRUE,
    '#default_value' => isset($instance->settings['body']['value']) ? $instance->settings['body']['value'] : '',
    '#format' => isset($instance->settings['body']['format']) ? $instance->settings['body']['format'] : NULL,
  );
  return $form;
}
