(function ($) {
/**
* @file
* Javascript, modifications of DOM.
*
* Manipulates links to include jquery load funciton
*/

Drupal.behaviors.bootstrap_barrio = {
  attach: function (context, settings) {
  // Capture barrio-modal class generated by Skinr.
  // This triggers block as modal.
    $('.barrio-modal').once(function () {
      var title = $(this).children('h2').text();
      $(this).after('<section id="btn-' + $(this).attr('id') + '" class="sideral-corner after"><a class="btn btn-primary btn-lg" data-target="#' + $(this).attr('id') + '" data-toggle="modal">' + title + '</a></section>');
    });
    $('.barrio-modal').attr("tabindex", "-1");
    $('.barrio-modal').attr("role", "dialog");
    $('.barrio-modal').attr("aria-hidden", "true");
    $('.barrio-modal h2').wrap('<div class="modal-header" />');
    $('.barrio-modal .modal-header').prepend('<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>');
    $('.barrio-modal .block-content').addClass('modal-body');
    $('.barrio-modal').append('<div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">' + Drupal.t('Close') + '</button></div>');
    $('.barrio-modal div').wrapAll('<div class="modal-dialog" />');
    $('.barrio-modal .modal-dialog div').wrapAll('<div class="modal-content" />');
    $('.barrio-modal').appendTo('body');
    // End of modal block definition

    // Capture barrio-dopdown class generated by Skinr.
    // This triggers block as dropdown.
    $('.barrio-dropdown').each(function () {
      var title = $(this).children('h2').text();
      $(this).children('h2').remove();
      $(this).prepend('<button class="btn dropdown-toggle" type="button" id="dropdown_' + $(this).attr('id') + '" data-toggle="dropdown">'+ title + '<span class="caret"></span></button>');
      $(this).children('.block-content').wrap('<ul class="dropdown-menu" role="menu" aria-labelledby="dropdown_' + $(this).attr('id') + '"><li role="presentation" /li></ul>');
    });
    // End of modal block definition

  // Prevent dropdown from closing when form inside
    $('.dropdown-menu').find('form').click(function (e) {
      e.stopPropagation();
    });

    $('.view-content').addClass('clearfix');
    $('.more-link a').addClass('btn btn-success');
    $('.not-front.page-user .main-container .btn').removeClass('btn-default');
    $('.not-front.page-user .main-container .btn').addClass('btn-info');

    $('.page-user-addressbook #commerce-addressbook-billing-default .views-row, .page-user-addressbook #commerce-addressbook-billing-list td .views-field').wrapInner('<address></address>');

  // Yamm code
    $(document).on('click', '.yamm .dropdown-menu', function(e) {
      e.stopPropagation()
    })
  }

}

}(jQuery));
