<?php
/**
 * @file
 * Cheetahmail Module
 */

// Admin backend:
    // Create module Installation Page
    // Create Module Configuration Page
    // Subscribe/ Unsubscribe email
// Frontend:
    // Subscribe/ Unsubscribe email.
/**
 * Implements hook_help().
 */
function cheetahmail_help($path, $arg) {
  if ($path == 'admin/help#cheetahmail') {
    return t('Experian Cheetahmail allows to integrate Drupal website with Cheetahmail marketing tools.');
  }
}

/**
 * Implements hook_menu().
 */
function cheetahmail_menu() {
  $items = array();

  // Cheetahmail settings.
  $items['admin/config/cheetahmail'] = array(
    'title' => 'Cheetahmail',
    'description' => 'Experian Cheetahmail configuration.',
    'position' => 'right',
    'weight' => -43,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/cheetahmail/api'] = array(
    'title' => 'Module settings',
    'description' => 'Experian Cheetahmail API configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cheetahmail_admin_menu_api_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'cheetahmail.admin.inc',
    'weight' => -20,
  );

  $items['admin/config/cheetahmail/campaignconfigs'] = array(
    'title' => 'Subscribe Campaign',
    'description' => 'Subcribe/Unsubscribe Campaign configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cheetahmail_admin_menu_campaignconfigs_form'),
    'access callback' => 'cheetahmail_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'cheetahmail.admin.inc',
  );

  // Pages.
  $items['cheetahmail/index'] = array(
    'title' => 'Subscribe Newsletters',
    'description' => 'Allows to subscribe for Newsletters.',
    'page callback' => 'drupal_get_form',
    'page arguments' =>  array('cheetahmail_subscribe_form'),
    'access callback' => 'cheetahmail_access',
    'access arguments' => array('cheetahmail subscribe_unsubscribe'),
    'file' => 'cheetahmail.pages.inc',
    'type' =>  MENU_NORMAL_ITEM,
    'menu_name' => 'navigation',
  );
  $items['cheetahmail/index/index'] = array(
    'title' => 'Subscribe Newsletters',
    'description' => 'Allows to subscribe for Newsletters.',
    'type' =>  MENU_DEFAULT_LOCAL_TASK,
  );
  $items['cheetahmail/index/unsubscribe'] = array(
    'title' => 'Unsubscribe Newsletters',
    'description' => 'Allows to unsubscribe from Newsletters.',
    'page callback' => 'drupal_get_form',
    'page arguments' =>  array('cheetahmail_unsubscribe_form'),
    'access callback' => 'cheetahmail_access',
    'access arguments' => array('cheetahmail subscribe_unsubscribe'),
    'file' => 'cheetahmail.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function cheetahmail_permission() {
  return array(
    'cheetahmail subscribe_unsubscribe' => array(
      'title' => t('Access Subscribe / Unsubscribe forms'),
      'description' => t('Allows to Subscribe / Unsubscribe emails for Newsletters.'),
    ),
  );
}

/**
 * Access callback for cheetahmail pages.
 *
 * @see cheetahmail_menu()
 */
function cheetahmail_access($string) {
  if (!variable_get('experian/cheetahmail/isactivated', FALSE)) {
    return FALSE;
  }

  return user_access($string);
}

/**
 * Implements hook_block_info().
 */
function cheetahmail_block_info() {
  $blocks['cheetahmail_subscribe'] = array(
    'info' => t('Subscribe Newsletters'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cheetahmail_block_view($delta = '') {
  switch ($delta) {
    case 'cheetahmail_subscribe':
      require_once 'cheetahmail.pages.inc';
      $block['subject'] = t("Subscribe Newsletters");
      $block['content'] = drupal_get_form('cheetahmail_subscribe_form');
      break;

  }

  return $block;
}
