language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - echo $TRAVIS_PHP_VERSION
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update
  - composer global require --prefer-source --no-interaction drush/drush:6.*

  # Build Codebase.
  - TESTDIR=$(pwd)
  - cd ..
  - git clone --branch 7.x --depth 1 http://git.drupal.org/project/drupal.git drupal
  - cd drupal
  # Patch Drupal so it can index traits.
  - curl https://www.drupal.org/files/issues/2508055-autoload-traits_0.patch | patch -p1

  # Disable sendmail (PHP)
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  # Disable sendmail (HHVM)
  - if [[ $TRAVIS_PHP_VERSION = "hhvm" ]]; then echo sendmail_path=`which true` >> /etc/hhvm/php.ini; fi

  # Increase the MySQL connection timeout on the PHP end.
  - |
    if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then
      echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

  # Enable APC
  - |
    if [[ $TRAVIS_PHP_VERSION < "5.5" ]]; then
      echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo "apc.shm_size=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:
  - ln -s $TESTDIR sites/all/modules/commerce_entity_plus

  # Update drupal core
  - drush si --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce" --yes
  - drush dl addressfield rules ctools entity views
  - drush en -y  simpletest commerce_entity_plus

  # Start server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done

script:
  # Run the tests
  - drush test-run --uri=http://127.0.0.1:8888 'Commerce Entity+'

  # Re-enable when trying to get CodeSniffer doesn't return a 403 anymore.
  #- /home/travis/.composer/vendor/bin/phpcs --standard=/home/travis/.composer/vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,inc,test,module,install --ignore=css/ $TRAVIS_BUILD_DIR/../drupal/modules/search_api
