<?php

/**
 * @file
 * Installation hooks for the module.
 */

/**
 * Implements hook_requirements().
 */
function sms_smsglobal_requirements($phase) {
  $requirements = array();
  // Ensure translations don't break at install time.
  $t = get_t();

  // Check if we have curl installed.
  $curl_available = function_exists('curl_init');

  $requirements['smsglobal_curl'] = array(
    'title' => $t('cURL'),
    'value' => $curl_available ? $t('Enabled') : $t('Not found'),
  );

  if (!$curl_available) {
    $requirements['smsglobal_curl'] += array(
      'severity' => REQUIREMENT_ERROR,
      'description' => $t("The SMSGlobal REST API library requires the PHP <a href='!curl_url'>cURL</a> library.", array('!curl_url' => 'http://php.net/manual/en/curl.setup.php')),
    );
  }

  // Only check the library at runtime.
  if ($phase == 'runtime') {
    $requirements['smsglobal'] = array(
      'title' => $t('SMSGlobal'),
    );

    $library = libraries_detect('smsglobal');
    // Check to see if the SMSGlobal client is installed.
    if (!empty($library['installed'])) {
      $requirements['smsglobal']['value'] = $library['version'];
      if ($library['version'] == '1.0.0') {
        // All good.
        $requirements['smsglobal']['severity'] = REQUIREMENT_OK;
      }
      else {
        // Not sure what this version is, but it should hopefully be good.
        $requirements['smsglobal']['severity'] = REQUIREMENT_WARNING;
        $requirements['smsglobal']['description'] = $t('This module has not been tested with version @version but it should hopefully be alright. Please report a bug if you run into problems.', array(
          '@version' => $library['version'],
        ));
      }
    }
    else {
      $requirements['smsglobal']['value'] = $t('Library not installed');
      $requirements['smsglobal']['severity'] = REQUIREMENT_ERROR;
      $requirements['smsglobal']['description'] = $t('The SMSGlobal REST client library is not installed, please see README.txt for installation instructions.');
    }
  }

  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function sms_smsglobal_uninstall() {
  // Remove our custom variable from the sms_bootstrap_routes variable.
  // @see sms_smsglobal_menu()
  $routes = variable_get('sms_bootstrap_routes');
  unset($routes['sms/smsglobal/incoming']);
  variable_set('sms_bootstrap_routes', $routes);
}
