<?php

/**
 * @file
 * Module hook implementations.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Inform the CTools plugin system about the location of a directory that should
 * be searched for files containing plugins of a particular type.
 */
function site_map_panels_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }

  return NULL;
}
