<?php
/**
 * @file
 * Set/unset test configuration and add quick admin links.
 */

/**
 * Implements hook_install().
 */
function uptime_simplytest_install() {
  $t = get_t();

  // Create a link to the settings page in the main menu.
  $item = array(
    'link_title' => $t('UpTime Widget settings'),
    'link_path' => 'admin/config/system/uptime',
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  menu_link_save($item);

  // Create a sample page.
  variable_set('uptime_ratio', 99.94);
  $results = array(
    'module_path' => drupal_get_path('module', 'uptime'),
  );
  $node = new stdClass();
  $node->uid = 1;
  $node->language = LANGUAGE_NONE;
  $node->type = 'page';
  $node->status = 1;
  $node->promote = 1;
  $node->title = $t('Demo of the UpTime Widget module.');
  $node->body[LANGUAGE_NONE][0]['value'] = $t('<p>Log in and check out the UpTime Widget settings <strong><em><a href="/admin/config/system/uptime">HERE</a></em></strong>.<br />The actual font color of the optional copyright notice can differ depending on the background color of the region the widget is in.</p><div class="style-settings-preview">' . theme('uptime', array('results' => $results)) . '</div><p>Note:<br />The example on the left does not get refreshed. Instead the block in the footer and the preview on the <a href="/admin/config/system/uptime">settings page</a> get updated on cron run or form submit.</p><!--break-->');
  $node->body[LANGUAGE_NONE][0]['format'] = 'full_html';
  node_save($node);

  // Create some admin quick links in the navigation menu.
  $item = array(
    'link_title' => $t('Configure Uptime block'),
    'link_path' => 'admin/structure/block/manage/uptime/uptime_widget/configure',
  );
  menu_link_save($item);
  $item = array(
    'link_title' => $t('Uptime settings'),
    'link_path' => 'admin/config/system/uptime',
  );
  menu_link_save($item);

  // New settings for testing.
  variable_set('uptime_api_key', 'u67898-e10c189beee66ab36cc2045c');
  variable_set('uptime_monitor_id', '775659447');
}

/**
 * Implements hook_uninstall().
 */
function uptime_simplytest_uninstall() {

  // Remove the admin quick links.
  $path = 'admin/structure/block/manage/uptime/uptime_widget/configure';
  menu_link_delete(NULL, $path);
  $path = 'admin/config/system/uptime';
  menu_link_delete(NULL, $path);
}
