
<?php // automatically generated by OM Subthemer module
$search_box_classes = '';
$highlighted_classes = '';
$content_classes = '';
$sidebar_second_classes = '';
$footer_classes = '';
?>


  <div class="wrapper-outer">
    <div id="header" class="wrapper"><div id="header-inner" class="wrapper-inner">
		  <?php print theme('identity', $identity_vars); ?>
		  <?php print theme('region_wrapper', _region_vars($page['search_box'], $search_box_classes, 0)); ?>		  
      <div class="clearfix"></div>
    </div></div> <!-- /#header-inner, /#header -->
    <div id="navigation" class="wrapper"><div id="navigation-inner" class="wrapper-inner">
		  <?php print theme('menu', $main_menu_vars); ?>
    </div></div> <!-- /#navigation-inner, /#navigation -->
    <div id="container" class="wrapper"><div id="container-inner" class="wrapper-inner">
		  <?php print theme('region_wrapper', _region_vars($page['highlighted'], $highlighted_classes, 1)); ?>
	  	<?php print theme('region_wrapper', _region_vars($page['sidebar_second'], $sidebar_second_classes, 1)); ?>
      <div id="main">
        <?php print $breadcrumb; ?>
        <div id="main-inner">
				    <?php print theme('content_elements', $content_elements_vars); ?>
				    <?php print render($page['help']); ?>
						<?php print $messages; ?>
				    <?php print theme('region_wrapper', _region_vars($page['content'], $content_classes, 0)); ?>
						<?php print $feed_icons; ?>
        </div> <!-- /main-inner -->
      </div> <!-- /main -->
      <div class="clearfix"></div>
    </div></div> <!-- /#container-inner, /#container -->

  </div> <!-- /.wrapper-outer -->
  <div class="footer_bottom">
    <div class="footer_bottom_triple">


        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_left'], $footer_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_middle'], $footer_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_right'], $footer_classes, 1)); ?>
 
    </div>
        <div class="clearfix"></div>
    <div class="footer_bottom_single">
      <?php print theme('region_wrapper', _region_vars($page['footer_bottom_single'], $footer_classes, 1)); ?>

    </div>
  </div>

