language: php
cache:
  bundler: true
  apt: true
php:
- 5.5
mysql:
  database: drupal
  username: root
  encoding: utf8
sudo: false
install:
- composer self-update
- composer --version
- mysql -e 'SET GLOBAL wait_timeout = 5400;'
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"
- echo 'max_execution_time = 120' >> drupal.php.ini;
- echo 'sendmail_path = /bin/true' >> drupal.php.ini;
- phpenv config-add drupal.php.ini
- phpenv rehash
- composer global require drush/drush:7.*
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- drush dl drupal --default-major=7 -y
- mv drupal-* drupal
- mkdir -p drupal/sites/all/modules/contrib/lightning_features
- mv lightning_* drupal/sites/all/modules/contrib/lightning_features/.
- mv tests drupal/.
- cd drupal
- drush make --no-core sites/all/modules/contrib/lightning_features/lightning_features.make -y
- drush si standard --db-url=mysql://root:@localhost/drupal -y
- drush en lightning_* -y
before_script:
- drush runserver --default-server=builtin 8080 &>/dev/null &
- cd tests
- composer install
- touch behat.local.yml
script:
- bin/behat --tags=lightning
notifications:
  slack:
    secure: Oh9eraFXE9rTucsK3Cxfq+TRa0eb+M1j0fnCJYLy+OYtGI30rnlrzB3fyxe2BR8ZGfafIbyAjSOQkoKEaohpsxauBAQNyrJUxwvjnVX7V05dHrczHAi2KBUiDKb4VZRp17XYAwoCE0jWYse3Y13Zn3bji0Vd/6WTDGPVjV7EbCtb73bck5Bc+vgnkuJsJG998eqbrT0f9YBBiKIOjeBSrhVuxNPkvqtWgmTSYVzgdEgvddXOWBkc96UVBTRJ8iZsfZHtyK+compORz85jm5UZfAgjFQb1gBswAKlZcYOLvaQXhcxyQKxuJ7u8W209nNUK+jPJ33eP8v7YOC1tESg6Jk0jZ8yWQKMcz/m+l6dYDU/OvXiraIl1sPjg30Oljrz7HWkCKNnOeqHMkuPbxMAxmdrlrgWLiaYXcAO+hmTwjbJegAvRVliR6tmw8Z9ODGH727M2UUnagLiyvhA2MHj7d4lF8a7mxMq2+HwsJwB+J9UYvIHCT24D01XvAVeaZjGwO6OGEVawx96OdFt0DR5PjW1e6UdvayQ9IHfK/8FcUf+N9LN4xkUjLiPq52Xu11RqM0zXu/VrdNpEH9/xjnBWpbxG94yxPu/MbJy/LWCSECn+9NZlVdl340jwFZ6ImHzWqmopST6XmqF1V+JfBPgz6XJvs03rItaiQ6mN8SVJSg=
matrix:
  fast_finish: true
