language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - sudo apt-get update > /dev/null
  - cd ..

  # Create a database for our Drupal site.
  - mysql -e "create database drupal;"

  # Install Drush
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-source --no-interaction drush/drush:dev-master
  - drush cc drush

  # Install Drupal
  - drush make --debug --yes role_provisioner/tests/role_provisioner_test.make.yml build
  - mv role_provisioner build/sites/all/modules

  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  # Move into our Drupal build.
  - cd build

  - drush si standard --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Testing" --yes
  - drush dis -y dblog
  - drush en -y libraries xautoload role_provisioner
  - drush en -y simpletest

script:
  - drush test-run --uri=http://127.0.0.1:8080 'Role provisioner' --xml --format=yaml
