<?php
/**
 * @file
 * Code for the nm_forums feature.
 */

include_once 'nm_forums.features.inc';


/**
 * Implements hook_help().
 */
function nm_forums_help($path, $arg) {
  switch ($path) {
    case 'admin/help#nm_forums':
      $content = array(
        '#group' => 'info',
        '#theme' => 'item_list',
        '#attributes' => array(
          'class' => array('nodemaker-apps-details'),
        ),
        '#items' => nm_forums_help_details(),
      );

      return render($content);
      break;
  }
}


/**
  * Content for hook_help().
  */
function nm_forums_help_details() {
  $items = array();
  $items[] = '<strong>' . t('.') . '</strong>  ' . t('');
  $items[] = '<strong>' . t('.') . '</strong>  ' . t('');
  $items[] = '<strong>' . t('.') . '</strong>  ' . t('');
  $items[] = '<strong>' . t('Issues?') . '</strong>  ' . t('Have a support question?  Find a bug?  !issue!', array('!issue' => '<a href="http://drupal.org/project/issues/nm_socialnetwork" title="NodeMaker Social Network Issue Queue" target="_blank">Please use the issue queue</a>'));
  return $items;
}