<?php

/**
 * Implements hook_browser_details_plugin().
 */
function bd_webbrowser_browser_details_plugin() {
    return array(
        'webbrowser' => array(
            'name' => 'webbrowser',
            'title' => 'Browser',
            'content' => 'bd_webbrowser_load_content',
	    'icon' => 'bd_webbrowser_load_icon'
        ),
    );
}

function bd_webbrowser_load_content() {
    $info = get_browser(null);
    return $info->browser . ' ' . $info->version;
}

function bd_webbrowser_load_icon() {
    $info = get_browser(null);
    return drupal_get_path('module', 'bd_webbrowser') . '/images/' . strtolower($info->browser) . '.png';
}
