<?php

/**
 * Implements hook_enable().
 */
function layouter_enable() {
  db_update('system')
    ->fields(array('weight' => 10))
    ->condition('type', 'module')
    ->condition('name', 'layouter')
    ->execute();
}

/**
 * Implements hook_uninstall().
 */
function layouter_uninstall() {
  variable_del('layouter_text_formats');
  variable_del('layouter_content_types');
  variable_del('layouter_image_styles');
  variable_del('layouter_uri_scheme');
}
