<?php
/**
 * @file
 * Hook implementations and callback functions of "ouibounce_exit_modal" module.
 */


/**
 * Implements hook_permission().
 */
function ouibounce_exit_modal_permission() {
  return array(
    'administer ouibounce exit modal' => array(
      'title' => t('Administer Ouibounce Exit Modal'),
      'description' => t('Allow the user administer Ouibounce Exit Modal settings'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ouibounce_exit_modal_menu() {
  $items = array();

  $items['admin/config/user-interface/ouibounce-exit-modal'] = array(
    'title' => 'Ouibounce Exit Modal',
    'description' => 'Allow the user administer Ouibounce Exit Modal settings',
    'file' => 'includes/ouibounce_exit_modal.menu.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ouibounce_exit_modal_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer ouibounce exit modal'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_library().
 */
function ouibounce_exit_modal_library() {
  return array(
    'ouibounce' => array(
      'title' => t('Ouibounce'),
      'website' => 'https://github.com/carlsednaoui/ouibounce/',
      'version' => '0.0.12',
      'js' => array(
        libraries_get_path('ouibounce') . "/build/ouibounce.min.js" => array(),
      ),
      'dependencies' => array(
        array('system', 'jquery'),
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function ouibounce_exit_modal_theme($existing, $type, $theme, $path) {
  return array(
    'ouibounce_exit_modal' => array(
      'template' => 'templates/ouibounce_exit_modal.modal',
      'arguments' => array(
        'title' => NULL,
        'body' => NULL,
        'footer' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ouibounce_exit_modal_block_info() {
  $blocks['ouibounce_exit_modal'] = array(
    'info' => t('Ouibounce Exit Modal'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_views().
 */
function ouibounce_exit_modal_block_view($delta) {
  $block = array();

  switch ($delta) {
    case 'ouibounce_exit_modal':
      $block = ouibounce_exit_modal_callback();
      break;
  }

  return $block;
}

/**
 * Callback function to get block contents.
 */
function ouibounce_exit_modal_callback() {
  $block = array();

  $body_id = variable_get('ouibounce_exit_modal_body', '');

  if (!empty($body_id)) {
    $block_details = explode('|', $body_id, 2);

    if (isset($block_details[0]) && isset($block_details[1])) {
      $body = ouibounce_exit_modal_render_block($block_details[0], $block_details[1]);
    }

    if (isset($body)) {
      ouibounce_exit_modal_load();

      $title = variable_get('ouibounce_exit_modal_title', '');
      $footer = variable_get('ouibounce_exit_modal_footer', 'No, thanks!');

      $content = theme('ouibounce_exit_modal', array(
        'title' => t($title),
        'body' => $body,
        'footer' => t($footer),
      ));

      $block['subject'] = '';
      $block['content'] = $content;
    }
  }

  return $block;
}

/**
 * Loads Ouibounce library and other necessary files and settings.
 */
function ouibounce_exit_modal_load() {
  $ouibounce_exit_modal_load = &drupal_static(__FUNCTION__);

  if (!isset($ouibounce_exit_modal_load)) {
    $path = drupal_get_path('module', 'ouibounce_exit_modal');

    drupal_add_library('ouibounce_exit_modal', 'ouibounce');
    drupal_add_css($path . '/css/ouibounce_exit_modal.css');

    $sensitivity = variable_get('ouibounce_exit_modal_sensitivity', 20);
    $aggressive_mode = variable_get('ouibounce_exit_modal_aggressive_mode', TRUE);
    $timer = variable_get('ouibounce_exit_modal_timer', 1000);
    $delay = variable_get('ouibounce_exit_modal_delay', 0);
    $cookie_expiration = variable_get('ouibounce_exit_modal_cookie_expiration', 0);
    $cookie_domain = variable_get('ouibounce_exit_modal_cookie_domain', '');
    $cookie_name = variable_get('ouibounce_exit_modal_cookie_name', 'viewedOuibounceModal');
    $sitewide_cookie = variable_get('ouibounce_exit_modal_sitewide_cookie', FALSE);

    $js_settings = array(
      'Sensitivity' => (int) $sensitivity,
      'AggressiveMode' => (bool) $aggressive_mode,
      'Timer' => (int) $timer,
      'Delay' => (int) $delay,
      'CookieExpiration' => (int) $cookie_expiration,
      'CookieDomain' => check_plain($cookie_domain),
      'CookieName' => check_plain($cookie_name),
      'SitewideCookie' => (bool) $sitewide_cookie,
    );

    drupal_add_js(array('ouibounceExitModal' => $js_settings), 'setting');
    drupal_add_js($path . '/js/ouibounce_exit_modal.js', array('scope' => 'footer'));

    $ouibounce_exit_modal_load = TRUE;
  }

  return $ouibounce_exit_modal_load;
}

/**
 * Render a block.
 */
function ouibounce_exit_modal_render_block($module, $delta) {
  // Invoke the block_view hook of the module.
  $block = module_invoke($module, 'block_view', $delta);

  // Get contextual links.
  $contextual_links = array();
  $contextual = module_exists('contextual') && user_access('access contextual links');
  if ($contextual) {
    if (isset($block['content']) && is_array($block['content']) && isset($block['content']['#contextual_links'])) {
      $contextual_links = $block['content']['#contextual_links'];
    }
  }

  // Render the block content.
  if (isset($block['content']) && is_array($block['content'])) {
    $block['content'] = drupal_render($block['content']);
  }

  // Go through in case we have actual content.
  if (!empty($block['content'])) {

    // Make sure subject is set.
    if (!isset($block['subject'])) {
      $block['subject'] = '';
    }

    global $theme_key;
    if (module_exists('block')) {
      $full_block = db_query("SELECT * FROM {block} WHERE module = :module AND delta = :delta AND theme = :theme", array(
        ':module' => $module,
        ':delta' => $delta,
        ':theme' => $theme_key
      ))->fetchObject();
    }
    if (!empty($full_block)) {
      if ($full_block->title == '<none>') {
        $block['subject'] = '';
      }
      elseif (!empty($full_block->title)) {
        $block['subject'] = $full_block->title;
      }
    }

    // i18n support.
    if (function_exists('i18n_block_block_view_alter')) {

      // Check language visibility.
      global $language;
      static $block_languages = FALSE;
      if (!$block_languages) {
        $block_languages = array();
        $result = db_query('SELECT module, delta, language FROM {i18n_block_language}');
        foreach ($result as $record) {
          $block_languages[$record->module][$record->delta][$record->language] = TRUE;
        }
      }
      if (isset($block_languages[$module][$delta]) && !isset($block_languages[$module][$delta][$language->language])) {
        return;
      }

      // Translate.
      if (!empty($full_block->i18n_mode)) {
        i18n_block_block_view_alter($block, $full_block);
        if (!empty($block['title'])) {
          $block['subject'] = $block['title'];
        }
      }
    }

    $block = (object) $block;
    $block->region = NULL;
    $block->module = $module;
    $block->delta = $delta;
    $elements = array(
      'elements' => array(
        '#block' => $block,
        '#children' => $block->content
      )
    );

    // Add contextual links.
    if ($contextual) {
      $elements['elements'] += array(
        '#contextual_links' => array_merge($contextual_links, array(
          'block' => array(
            'admin/structure/block/manage',
            array($block->module, $block->delta)
          )
        ))
      );
    }

    return theme('block', $elements);
  }
}
