language: php
php:
  - 5.3
before_install:
- pear install pear/PHP_CodeSniffer
- phpenv rehash
- sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
- source $HOME/.bashrc
- composer global require drush/drush:6.*
- composer global update
- drush --version
- drush dl coder --destination=$HOME/.drush
- ln -s $TRAVIS_BUILD_DIR $HOME/.drush/rebuild
- drush cache-clear drush
script:
- drush drupalcs rebuild.drush.inc
- drush drupalcs src
- phpunit
