<?php

/**
 * @file
 * The main file of the Mail Tester module.
 */

/**
 * Implements hook_permission().
 */
function mail_tester_permission() {
  return array(
    'use mail tester' =>  array(
      'title' => t('Use Mail Tester'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mail_tester_menu() {
  $items['admin/reports/mail_tester'] = array(
    'title' => 'Mail Tester',
    'page callback' => 'mail_tester_admin_reports_mail_tester',
    'access arguments' => array('use mail tester'),
    'file' => 'mail_tester.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_mail().
 */
function mail_tester_mail($key, &$message, $params) {
  switch ($key) {

    case 'test_message':
      $message['subject'] = t("Drupal Mail Tester Module for !site_name", array("!site_name" => variable_get('site_name', 'a website')));
      $message['body'] = array(
        "Hello Mail Tester,",
        "This is just a test message to see what do you think about my server configuration.",
        "Hope everything is ok.",
        "Bye",
      );
      break;

  }
}
