language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  include:
    - php: 5.4
      env: dependencies=lowest

install:
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; else composer update -n; fi;

after_script:
  - php vendor/bin/coveralls
