<?php
/**
 * Implements hook_pane_plugins
 *
 * @return array
 */
function pane_entity_host_pane_plugins() {
  $plugins = array();

  $plugins['pane_entity_host'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'pane_entity_host') . '/plugins/panes',
      'file' => 'pane_entity_host.inc',
      'class' => 'pane_entity_host',
      'parent' => 'pane_base',
    ),
  );

  return $plugins;
}

/**
 * Implements hook_pane_registry
 * 
 * @return array
 */
function pane_entity_host_pane_registry() {
  $registry = array();

  $registry['entity_host'] = array(
    'title' => t('Entity host'),
    'description' => t('Entity host'),
    'plugin' => 'pane_entity_host',
  );

  return $registry;
}