
<?php // automatically generated by OM Subthemer module
$header_block_classes   = 'row rows-2 row-2-1 row-1 row-first';
$highlighted_classes    = 'row rows-1 row-1-1 row-1 row-first row-last';
$sidebar_first_classes  = 'column columns-3 column-3-1 column-1 column-first';
$content_classes        = 'row rows-5 row-5-1 row-1 row-first';
$sidebar_second_classes = 'column columns-3 column-3-3 column-3 column-last';
$footer_classes         = 'row rows-1 row-1-1 row-1 row-first row-last';
?>

<div id="page-wrapper" class="wrapper wrapper-level-1 wrapper-page-wrapper row rows-1 row-1-1 row-1 row-first row-last wrapper-outer">
	<div id="navigation" class="wrapper wrapper-level-2 wrapper-navigation row rows-5 row-5-2 row-2"><div id="navigation-inner" class="wrapper-inner">
		<?php print theme('menu', $main_menu_vars); ?>
	</div></div><!-- /#navigation-inner, /#navigation -->
	<div id="header" class="wrapper wrapper-level-2 wrapper-header row rows-5 row-5-1 row-1 row-first"><div id="header-inner" class="wrapper-inner">
		<?php print theme('identity', $identity_vars); ?>
		<?php print theme('region_wrapper', _region_vars($page['header_block'], $header_block_classes, 0)); ?>
	</div></div><!-- /#header-inner, /#header -->
	<div id="highlighted-wrapper" class="wrapper wrapper-level-2 wrapper-highlighted-wrapper row rows-5 row-5-3 row-3"><div id="highlighted-wrapper-inner" class="wrapper-inner">
		<?php print theme('region_wrapper', _region_vars($page['highlighted_left'], $highlighted_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['highlighted_middle'], $highlighted_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['highlighted_right'], $highlighted_classes, 1)); ?>
        
        
	</div></div><!-- /#highlighted-wrapper-inner, /#highlighted-wrapper -->
	<div id="container" class="wrapper wrapper-level-2 wrapper-container row rows-5 row-5-4 row-4"><div id="container-inner" class="wrapper-inner">

		<div id="main" class="wrapper wrapper-level-3 wrapper-main column columns-3 column-3-2 column-2">
			<?php print $breadcrumb; ?>
			<div id="main-inner" class="wrapper wrapper-level-4 wrapper-main-inner row rows-2 row-2-1 row-1 row-first">
				<?php print theme('content_elements', $content_elements_vars); ?>
				<?php print render($page['help']); ?>
				<?php print $messages; ?>
				<?php print theme('region_wrapper', _region_vars($page['content'], $content_classes, 0)); ?>
				<?php print $feed_icons; ?>
			</div><!-- /#main-inner -->
		</div><!-- /#main -->
		<?php print theme('region_wrapper', _region_vars($page['sidebar_second'], $sidebar_second_classes, 1)); ?>
		<div class="clearfix"></div>
	</div></div><!-- /#container-inner, /#container -->
</div><!-- /#page-wrapper -->


	<div id="footer-wrapper" class="wrapper wrapper-level-2 wrapper-footer-wrapper row rows-5 row-5-5 row-5 row-last"><div id="footer-wrapper-inner" class="wrapper-inner">

        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_left'], $footer_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_right'], $footer_classes, 1)); ?>
        <?php print theme('region_wrapper', _region_vars($page['footer_bottom_single'], $footer_classes, 1)); ?>
        <div class="clearfix"></div>
        

	</div></div><!-- /#footer-wrapper-inner, /#footer-wrapper -->
