<?php

/**
 * @file
 * Provide integration with amoCRM via webhooks.
 */

define('AMOCRM_TYPE_LEAD', 'leads');
define('AMOCRM_TYPE_CONTACT', 'contacts');
define('AMOCRM_TYPE_COMPANY', 'companies');

/**
 * Implements hook_menu().
 */
function amocrm_menu() {
  $items['amocrm'] = array(
    'page callback' => 'amocrm_webhook_callback',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_amocrm_leads().
 */
function amocrm_amocrm_leads($data, $action, $account) {
  if (module_exists('rules')) {
    rules_invoke_event('amocrm_leads_' . $action, $data);
  }
}

/**
 * Implements hook_amocrm_contacts().
 */
function amocrm_amocrm_contacts($data, $action, $account) {
  if (module_exists('rules')) {
    rules_invoke_event('amocrm_contacts_' . $action, $data);
  }
}

/**
 * Implements hook_amocrm_companies().
 */
function amocrm_amocrm_companies($data, $action, $account) {
  if (module_exists('rules')) {
    rules_invoke_event('amocrm_companies_' . $action, $data);
  }
}

/**
 * Page callback for 'amocrm' path.
 */
function amocrm_webhook_callback() {
  $entity = '';

  if (isset($_POST[AMOCRM_TYPE_LEAD])) {
    $entity = AMOCRM_TYPE_LEAD;
  }
  elseif ($_POST[AMOCRM_TYPE_CONTACT]) {
    $entity = AMOCRM_TYPE_CONTACT;
  }

  if (!$entity || empty($_POST)) {
    watchdog('amoCRM', 'Wrong post arguments: %post', array('%post' => serialize($_POST)), WATCHDOG_ERROR);
    drupal_exit();
  }

  $action = key($_POST[$entity]);
  $data = $_POST[$entity][$action];
  $account = $_POST['account'];

  if (!empty($data[0]['type']) && $data[0]['type'] == 'company') {
    $entity = AMOCRM_TYPE_COMPANY;
  }

  foreach ($data as $item) {
    module_invoke_all('amocrm_' . $entity, $item, $action, $account);
  }

  drupal_exit();
}
