<?php
/**
 * @file
 * Clean up variables.
 */
/**
 * Implements hook_uninstall().
 */
function lyris_devel_uninstall() {
  // Remove any variables we set.
  variable_del('lyris_devel_error_handler');
  variable_del('lyris_devel_log_api');
  variable_del('lyris_devel_show_queries');
  variable_del('lyris_devel_show_line');
  variable_del('lyris_devel_show_server');
  variable_del('lyris_devel_show_form_weights');
  variable_del('lyris_devel_debug');
}
