<?php

define('IN_FIELD_LABELS_DEFAULT_FORMS', "user-register-form\nuser-login");

/**
 * Implement hook_library()
 */
function in_field_labels_library() {
  $library['jquery.infieldlabel'] = array(
    'title' => 'In Field Label',
    'website' => 'http://fuelyourcoding.com/scripts/infield',
    'version' => '0.1.2',
    'js'    => array(
      drupal_get_path('module', 'in_field_labels') . '/js/jquery.infieldlabel.min.js' => array(),
    ),
  );
  return $library;
}

/**
 * Implement_hook_menu()
 */
function in_field_labels_menu() {
  $items['admin/config/user-interface/in-field-labels'] = array(
    'title' => 'In Field Labels',
    'description' => 'Settings for In Field Labels library',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('in_field_labels_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'in_field_labels.admin.inc',
  );
  return $items;
}

/**
 * Implement hook_form_alter()
 */
function in_field_labels_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form['#id'], array_map('trim', explode("\n", variable_get('in_field_labels_forms', IN_FIELD_LABELS_DEFAULT_FORMS))))) {
    $form['#attached']['library'][] = array('in_field_labels', 'jquery.infieldlabel');

    // This has the potential of overriding Drupal.settings.in_field_labels.forms
    // with single last-added form-id. Need to find a way to allow multiple
    // forms id be added to Drupal.settings.in_field_labels.forms
    $form['#attached']['js'][] = array(
      'data' => array(
        'in_field_labels' => array(
          'forms' => array(
            $form['#id'],
          ),
        ),
      ),
      'type' => 'setting',
    );
    $form['#attached']['js'][] = drupal_get_path('module', 'in_field_labels'). '/js/in_field_labels.js';
    $form['#attached']['css'][] = array(
      'data' => " #{$form['#id']} .form-item {
          position: relative;
        }
        #{$form['#id']} label {
          position: absolute;
        }",
      'type' => 'inline',
    );
  }
}

