<?php

/**
 * @file
 * Hooks provided by the module Language Selection Page.
 */

/**
 * @addtogroup hooks
 * @{
 */

/**
 * This function let you change the links generated by the module.
 *
 * @param $data
 *   These data are used by the template language-selection-page-body.tpl.php
 *   It's an array of informations related to this module.
 *
 *   - $data['from'] contains an array with these properties:
 *     - text: the URL in text of the page it's coming from
 *     - query: the query of this url, if any
 *     - url: the URL in text, already generated with url()
 *     - link: the HTML link, already generated with l()
 *
 *   - $data['links'] contains an array of arrays for each
 *    enabled language with these properties:
 *     - language: the Drupal's language object
 *     - from: the url it's coming from
 *     - query: the query parameters if any
 *     - url: the URL in text already generated with url()
 *     - link: the HTML link, already generated with l()
 */
function hook_language_selection_page_data_alter(&$data) {

}

/**
 * @} End of "addtogroup hooks".
 */
