<?php

/**
 * @file
 * Basic integration with the Drupal API
 * It also integrates with Rules and Commerce
 */

/*
 * Commerce Invoices include directory path
 */
define("COMMERCE_INVOICES_INCLUDE", DRUPAL_ROOT.'/'.drupal_get_path("module", "commerce_invoices").'/includes/');
define("COMMERCE_INVOICES_THEME", DRUPAL_ROOT.'/'.drupal_get_path("module", "commerce_invoices").'/theme/');


/*
 * Main business logic
 */
require_once COMMERCE_INVOICES_INCLUDE.'commerce_invoices.main.inc';

/*
 * Forms and other UI elements
 */
require_once COMMERCE_INVOICES_INCLUDE.'commerce_invoices.ui.inc';

/*
 * Theme functions and display logic
 */
require_once COMMERCE_INVOICES_THEME.'commerce_invoices.theme.inc';

/**
 * Rules Integration
 */
require_once COMMERCE_INVOICES_INCLUDE.'commerce_invoices.rules.inc';

/**
 * Commerce API Integration
 */
require_once COMMERCE_INVOICES_INCLUDE.'commerce_invoices.commerce.inc';



/**
 * Implements hook_permission().
 */
function commerce_invoices_permission() {
  return array(
      'add invoices' => array(
          'title' => 'Add Invoices',
          'description' => 'Allow users to add invoices',
      ),
      'manage invoices' => array(
          'title' => t('Manage Invoices'),
          'description' => 'Allow users to view invoices',
      ),
  );
}

/**
 * Implements hook_menu().
 */
function commerce_invoices_menu() {

  $items['admin/commerce/invoices'] = array(
      'title' => 'Invoices',
      'description' => 'Manage Invoices',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file path' => drupal_get_path('module', 'system'),
      'file' => 'system.admin.inc',
      'weight' => -15,
  );

  $items['admin/commerce/invoices/add-invoice'] = array(
      'title' => 'Add Invoice',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('commerce_invoices_add_invoice'),
      'access arguments' => array('add invoices'),
      'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/commerce/invoices/manage-invoices'] = array(
      'title' => 'Manage Invoices',
      'page callback' => 'commerce_invoices_manage_invoices',
      'access arguments' => array('manage invoices'),
      'type' => MENU_NORMAL_ITEM,
  );

  $items['user/invoices/pay'] = array(
      'title' => 'Pay Invoice',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('commerce_invoices_pay_invoice'),
      'access arguments' => array('access checkout'),
      'type' => MENU_CALLBACK,
  );

  $items['commerce-invoices/%/%'] = array(
      'title' => 'Checkout and Pay Invoice',
      'page callback' => 'commerce_invoices_create_order',
      'page arguments' => array(1, 2),
      'access arguments' => array('access checkout'),
      'type' => MENU_CALLBACK,
  );

  return $items;
}