<?php
/**
 * @file
 * Setup the module on initial installation and
 * clean up when the module is uninstalled.
 */

/**
 * Implements hook_schema().
 *
 * Create a table to manage our settings.
 */
function random_weight_schema() {
  $schema['random_weight'] = array(
    'description' => 'Stores settings for the random weight module.',
    'fields' => array(
      'type' => array(
        'description' => 'The {node_type} for the setting',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'last_run' => array(
        'description' => 'Last run time.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'frequency' => array(
        'description' => 'Callback function to calculate run frequency.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'weight_range' => array(
        'description' => 'Stores the range of the weights per content type',
        'type' => 'int',
        'unsigned' => FALSE,
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array(
      'type',
    ),
  );

  return $schema;
}
