<?php

/**
 * @file
 *   Builds links to post pages to twitter.
 */

/**
 * Implementation of hook_update_N().
 */
function tweet_update_6001() {
  // The settings pages moved, so we need to rebuild the menu router cache.
  menu_cache_clear_all();
}

/**
 * Implements hook_uninstall().
 */
function tweet_uninstall() {
  variable_del('tweet_identica_image');
  variable_del('tweet_node_vocabs');
  variable_del('tweet_new_window');
  variable_del('tweet_exclude');
  variable_del('tweet_format');
  variable_del('tweet_teaser');
  variable_del('tweet_image');
  variable_del('tweet_sites');
  variable_del('tweet_types');
  variable_del('tweet_node');
  variable_del('tweet_text');
}
