<?php

/**
 * @file
 * Drupal module for React library integration
 */

define('REACT_VENDOR_URL', 'http://facebook.github.io/react/');
define('REACT_DOWNLOAD_URL', 'http://facebook.github.io/react/downloads/react-0.10.0.zip');

/**
 * Implements hook_libraries_info().
 *
 * @see hook_libraries_info()
 */
function react_libraries_info() {

  $minified_variant = array(
    'js' => array(
      'react.min.js',
    ),
  );

  $libraries['react'] = array(
    'name' => 'react',
    'vendor url' => REACT_VENDOR_URL,
    'download url' => REACT_DOWNLOAD_URL,
    'path' => 'build',
    // The version is in the line 2 of the file. It looks like this currently:
    // * React v0.10.0
    'version arguments' => array(
      'file' => 'build/react.min.js',
      'pattern' => '@React v([\d\.]+)@',
      'lines' => 3,
      'cols' => 30,
    ),
    'files' => $minified_variant,
    'variants' => array(
      'minified' => array(
        'files' => $minified_variant,
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'react.js',
          ),
        ),
      ),
    ),
  );

  // Setting to *replace* the core library.
  if (variable_get('react_with_addons', FALSE)) {
    $libraries['react']['files']['js'] = array(
      'react-with-addons.js',
    );
    $libraries['react']['variants']['minified']['files']['js'] = array(
      'react-with-addons.min.js',
    );
    $libraries['react']['variants']['source']['files']['js'] = array(
      'react-with-addons.min.js',
    );
  }

  // Setting to *add* the extra JS file JSXTransformer.js
  if (variable_get('react_with_jsxtransformer', TRUE)) {
    $libraries['react']['files']['js'][] = 'JSXTransformer.js';
    $libraries['react']['variants']['minified']['files']['js'][] = 'JSXTransformer.js';
    $libraries['react']['variants']['source']['files']['js'][] = 'JSXTransformer.js';
  }

  return $libraries;
}

/**
 * Implements hook_menu().
 *
 * @see hook_menu()
 */
function react_menu() {

  $items['admin/config/development/react'] = array(
    'title' => 'React',
    'description' => 'Configuration for React',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('react_admin_settings'),
    'file' => 'react.admin.inc',
  );

  return $items;
}
