<?php

/**
 * @file
 * Provides an interface for creating blocks containing information about the
 * current search with links to remove keywords.
 */

/**
 * Implements hook_current_search_items().
 */
function current_search_links_current_search_items() {
  return array(
    'active_links' => array(
      'handler' => array(
        'label' => t('Active items links'),
        'class' => 'CurrentSearchItemActiveLinks',
      ),
    )
  );
}
