<?php

/**
 * @file
 * Override "Powered by" block with your personal infos.
 *
 * Powered Override
 *
 * Drupal 7 version:
 * Written by Gianluca Agnocchetti (hiryu)
 */

/**
 * Implements hook_install().
 */
function powered_override_install() {
  // Nothing to do.
}

/**
 * Implements hook_uninstall().
 */
function powered_override_uninstall() {
  variable_del('powered_override_setup_infos');
}
