---
dependencies:
  - 'git+http://github.com/GetValkyrie/ansible-role-drush.git,,getvalkyrie.drush'

galaxy_info:
  author: ergonlogic
  description: Aegir - Drupal hosting and provisioning
  company: "GetValyrie"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
    - development
    - web
