<?php

/**
 * implement hook_exchange_rate_country_info 
 */
function costa_rica_exchange_rate_country_info() {
  return _costa_rica_get_config( null );
}

/**
 * implement hook_exchange_rate_get_config 
 */
function costa_rica_exchange_rate_get_config( $country, $index = null ) {
  if ( $country == 'costa_rica' ) {
    return _costa_rica_get_config( $index );
  }
}

function _costa_rica_get_config( $index = null ) {
  // Each bank has an array of paremeters used for custom implementation
  $config = array(
    'costa_rica' => array(
      'label' => t( 'Costa Rica' ),
      'currencies' => array(
        'USD' => "United States Dollar",
        'EUR' => "Euro",
        'NIO' => 'Cordoba'
      ),
      'official_bank' => array(
        'currencies' => array(
          'USD' => array( 0 => 317, 1 => 318 ),
          'EUR' => array( ),
          'NIO' => array( )
        ),
        'label' => 'BCCR'
      ),
      'banks' => array(
        'Banco Crédito Agrícola de Cartago' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3146,
              1 => 3206
            )
          )
        ),
        'Banco de Costa Rica' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3148,
              1 => 3207
            )
          )
        ),
        'Banco Nacional' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3149,
              1 => 3208
            )
          )
        ),
        ' Banco Popular' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3179,
              1 => 3209
            )
          )
        ),
        'Banco BCT' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3151,
              1 => 3210
            )
          )
        ),
        'Banco HSBC S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3152,
              1 => 3211
            )
          )
        ),
        'Banco Citibank Costa Rica' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3153,
              1 => 3212
            )
          )
        ),
        'Bansol' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3191,
              1 => 3225
            )
          )
        ),
        'Banco CMB' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3154,
              1 => 3213
            )
          )
        ),
        'Banco Cathay' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3180,
              1 => 3214
            )
          )
        ),
        'Banco Bac San José' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3181,
              1 => 3215
            )
          )
        ),
        'Banco Lafise' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3183,
              1 => 3217
            )
          )
        ),
        'Banco Improsa' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3184,
              1 => 3218
            )
          )
        ),
        'Banco Promerica' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3186,
              1 => 3220
            )
          )
        ),
        'Scotiabank C.R.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3187,
              1 => 3221
            )
          )
        ),
        'Banco General Costa Rica S.A' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3566,
              1 => 3568
            )
          )
        ),
        'Financiera Comeca' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3189,
              1 => 3223
            )
          )
        ),
        'Financiera Multivalores' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3190,
              1 => 3224
            )
          )
        ),
        'Financiera G&T Continental Costa Rica S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3593,
              1 => 3594
            )
          )
        ),
        'Financiera Cafsa' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3193,
              1 => 3227
            )
          )
        ),
        'Financiera DESYFIN S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3341,
              1 => 3342
            )
          )
        ),
        'Financiera Financia S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3593,
              1 => 3594
            )
          )
        ),
        'Mutual Alajuela' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3194,
              1 => 3228
            )
          )
        ),
        'Mutual Cartago' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3195,
              1 => 3229
            )
          )
        ),
        'Cooperativa Credecoop' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3196,
              1 => 3230
            )
          )
        ),
        'Cooperativa Coocique' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3197,
              1 => 3231
            )
          )
        ),
        'Cooperativa San Marcos' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3198,
              1 => 3232
            )
          )
        ),
        'Coopenae' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3200,
              1 => 3233
            )
          )
        ),
        'Coopealianza' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3289,
              1 => 3290
            )
          )
        ),
        'Coopesanramon R.L.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3345,
              1 => 3346
            )
          )
        ),
        'Coopeorotina R.L.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3361,
              1 => 3363
            )
          )
        ),
        'Coopeservidores R.L.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3563,
              1 => 3567
            )
          )
        ),
        'CoopeAnde N° 1 R.L' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3597,
              1 => 3598
            )
          )
        ),
        'Casa Cambio Tele Dólar' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3201,
              1 => 3271
            )
          )
        ),
        'Casa Cambio Global Exchange' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3203,
              1 => 3277
            )
          )
        ),
        'Casa Cambio Soluciones Monetarias S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3556,
              1 => 3562
            )
          )
        ),
        'Casa de Cambio Latin American Exchange, S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 19860,
              1 => 19861
            )
          )
        ),
        'Puesto de Bolsa Aldesa Valores' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3204,
              1 => 3278
            )
          )
        ),
        'BN Valores Puesto Bolsa' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3327,
              1 => 3338
            )
          )
        ),
        'Acobo Puesto de Bolsa S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3427,
              1 => 3428
            )
          )
        ),
        'INS Valores Puesto de Bolsa S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3549,
              1 => 3550
            )
          )
        ),
        'BCT Valores Puesto de Bolsa S.A.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 3552,
              1 => 3553
            )
          )
        ),
        'Mercado Valores de C.R. P.B.' => array(
          'currencies' => array(
            'USD' => array(
              0 => 18922,
              1 => 18923
            )
          )
        ),
        'Popular Valores Puesto de Bolsa' => array(
          'currencies' => array(
            'USD' => array(
              0 => 19728,
              1 => 19729
            )
          )
        )
      )
    )
  );

  if ( !isset( $index ) ) {
    return $config;
  }
  else {
    return $config[ 'costa_rica' ][ $index ];
  }
}

function costa_rica_exchange_rate_name( $name ) {
  if ( $name == 'costa_rica' ) {
    return t( "Costa Rica" );
  }
}

/**
 * Implementation of hook_cron
 */
function costa_rica_cron() {
  //Enable each module i.e Costa Rica can be executed isolate , useful with elysia cron module
  costa_rica_exchange_rate_cron();
}

/*
 * Implementation of hook_exchange_rate_cron
 */
function costa_rica_exchange_rate_cron() {

  $parameters = array(
    'tcIndicador' => 0,
    'tcFechaInicio' => date( 'd/m/Y' ),
    'tcFechaFinal' => date( 'd/m/Y', time() + 3600 * 24 ),
    'tcNombre' => 'Drupal Exchange Rate',
    'tnSubNiveles' => 'N'
  );

  $currencies = variable_get( 'costa_rica_currencies', array( ) );
  $soap_client = new SoapClient( "http://indicadoreseconomicos.bccr.fi.cr/IndicadoresEconomicos/WebServices/wsIndicadoresEconomicos.asmx?WSDL" );

  foreach ( $currencies as $key => $currency ) {

    if ( !$currency ) {
      continue;
    }

    // Get official exchange rate in Costa Rica
    $official_bank = _costa_rica_get_config( 'official_bank' );

    //Get the first parameter for current currency of official bank - buy exchange rate indicator
    $parameters[ 'tcIndicador' ] = $official_bank[ 'currencies' ][ $key ][ 0 ];

    $resultado = $soap_client->__call( 'ObtenerIndicadoresEconomicosXML', array( $parameters ) );

    $xml = simplexml_load_string( $resultado->ObtenerIndicadoresEconomicosXMLResult );

    //Buy rate 
    $buy = $xml->INGC011_CAT_INDICADORECONOMIC->NUM_VALOR;

    //Get the first parameter for current currency of official bank - sell exchange rate indicator
    $parameters[ 'tcIndicador' ] = $official_bank[ 'currencies' ][ $key ][ 1 ];

    $resultado = $soap_client->__call( 'ObtenerIndicadoresEconomicosXML', array( $parameters ) );
    $xml = simplexml_load_string( $resultado->ObtenerIndicadoresEconomicosXMLResult );

    //Sell Rate
    $sell = $xml->INGC011_CAT_INDICADORECONOMIC->NUM_VALOR;

    //Insert record in exchage_record historical
    $record = array(
      "country" => 'costa_rica',
      "bank" => $official_bank[ 'label' ], // Official Bank
      "currency" => $currency,
      "date" => time(),
      "buy" => $buy,
      "sell" => $sell,
    );

    drupal_write_record( 'exchange_rate_historical', $record );
    //End insert record
  }

  //Process banks exchage rate
  $banks = _costa_rica_get_config( 'banks' );

  //Shuffle banks to request in diff order always
  $shuffle_banks = array( );
  foreach ( $banks as $bank_name => $bank_args ) {
    $shuffle_banks[ ] = array( $bank_name => $bank_args );
  }
  
  shuffle( $shuffle_banks );

  $enabled_banks = array_filter( variable_get( 'costa_rica_banks', array( ) ) );

  foreach ( $currencies as $key => $currency ) {

    if ( !$currency ) {
      continue;
    }

    foreach ( $shuffle_banks as $bank ) {
      foreach ( $bank as $bank_name => $bank_args ) {

        //Only process banks enabled in configuration.
        if ( !in_array( $bank_name, $enabled_banks ) ) {
          continue;
        }
        
        $parameters[ 'tcIndicador' ] = $bank_args[ 'currencies' ][ $currency ][ 0 ];
        $resultado = $soap_client->__call( 'ObtenerIndicadoresEconomicosXML', array( $parameters ) );
        $xml = simplexml_load_string( $resultado->ObtenerIndicadoresEconomicosXMLResult );

        $buy = $xml->INGC011_CAT_INDICADORECONOMIC->NUM_VALOR;

        $parameters[ 'tcIndicador' ] = $bank_args[ 'currencies' ][ $currency ][ 1 ];
        $resultado = $soap_client->__call( 'ObtenerIndicadoresEconomicosXML', array( $parameters ) );
        $xml = simplexml_load_string( $resultado->ObtenerIndicadoresEconomicosXMLResult );

        $sell = $xml->INGC011_CAT_INDICADORECONOMIC->NUM_VALOR;

        //Insert record in exchage_record historical
        $record = array(
          "country" => 'costa_rica',
          "bank" => $bank_name,
          "currency" => $currency,
          "date" => time(),
          "buy" => $buy,
          "sell" => $sell,
        );

        drupal_write_record( 'exchange_rate_historical', $record );
        //End insert record
      }
    }
  }
}