---
language: python
python: "2.7"

env:
  - SITE=test.yml

notifications:
  slack:
    secure: "AIKMmxzYL6xbpY4uN8BxhXDs+Em/PpVHy4OZcnal6+jBKW5xNNPOXiZ1KyZuaC40sYzW43CC3xUYS8KxQ1JvAvkZoGQp6XgLBV5xePNd5vVx1+v/vwzCOSRaWU9wse/ROYYxHJCZ4Hbf5w+k0K2SGQwtKqlzNwcfL8OcBmattdA="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl
  # Avoid harmless (but annoying) warnings.
  - mkdir ~/.python-eggs
  - chmod 700 ~/.python-eggs
  # Completely remove mysql
  - sudo apt-get remove -y --purge mysql-server mysql-client mysql-common
  - sudo apt-get autoremove -y
  - sudo apt-get autoclean
  - sudo rm -rf /var/lib/mysql
  - sudo rm -rf /root/.my.cnf

install:
  # Install Ansible from sources.
  - curl https://raw.githubusercontent.com/GetValkyrie/ansible-bootstrap/master/install-ansible.sh|sudo /bin/sh

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Install required dependencies.
  - ansible-galaxy install http://github.com/getvalkyrie/ansible-role-mysql,,getvalkyrie.mysql
  - ansible-galaxy install http://github.com/getvalkyrie/ansible-role-drush,,getvalkyrie.drush

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check if Aegir is installed and working.
  - sudo -u aegir -H drush @hm status | grep eldir
