<?php
/**
 * @file
 * Installation file for message bar.
 */


/**
 * Implements of hook_uninstall().
 *
 * Remove all the variables saved in the database.
 */
function headbar_uninstall() {
  //Delete all variables.
  variable_del('headbar_color');
  variable_del('headbar_color_hover');
  variable_del('headbar_delaytime');
  variable_del('headbar_text');
  // Clear the cache tables.
  drupal_flush_all_caches();
}
