<?php

/**
 * @file
 * diff_different.install
 *
 * Install and uninstall functions for the Diff Different module.
 */

/**
 * Implements hook_enable().
 */
function diff_different_enable() {
  drupal_set_message(st("Thank you for installing Diff Different. To complete the installation visit the <a href='@url_config'>configuration page</a>.", array(
    '@url_config' => url('admin/config/content/diff-different'))
  ));
}

/**
 * Implements hook_uninstall().
 */
function diff_different_uninstall() {
  // Delete all diff_different_* variables at once.
  db_query("DELETE FROM {variable} WHERE name LIKE 'diff_different_%%'");
}
