<?php

/**
 * Implements hook_menu().
 */
function plus_url_menu() {
  $items = array();

  $items['admin/config/search/plus-url'] = array(
    'title' => 'Google+ vanity url',
    'description' => 'The description of the menu item. It is used as title attribute and on the administration overview page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plus_url_admin_form'),
    'access arguments' => array('administer plus_url'),
  );
  // This menu item does actually not do much other than redirecting. It is not
  // possible to make a menu item in drupal that would simply respond to
  // http://example.com/+ because of how drupal's .htacces is set up. This item
  // exists to make it possible for the site owner to have an item in a menu
  // that redirects to the configured Google+ account.
  $items['googleplus'] = array(
    'title' => 'Google+',
    'description' => 'My profile on Google+.',
    'page callback' => 'plus_url_redirect',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
    'menu_name' => 'main-menu',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function plus_url_permission() {
  return array(
    'administer plus_url' => array(
      'title' => t('administer plus_url'),
      'description' => t('Edit the profile ID to point to at Google+'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function plus_url_init() {
  if ('/+' === $_SERVER['REQUEST_URI']) {
    plus_url_redirect();
  }
}

/**
 * Redirects to the configured Google+ account if there is a configured profile
 * ID. If no profile ID has been configured yet, the user is taken to the front
 * page.
 */
function plus_url_redirect() {
  $profile_id = variable_get('plus_url_profile_id', FALSE);
  if (!$profile_id) {
    // Go to the front page. There is not much we can do without the profile
    // ID.
    drupal_goto('<front>');
  }
  $profile_section = variable_get('plus_url_section', 'about');
  drupal_goto("https://plus.google.com/$profile_id/$profile_section", array(), '301');
}

/**
 * Settings form.
 * Configures Google+ profile id and section to go to.
 */
function plus_url_admin_form($form, &$form_state) {
  $form = array();
  $form['instructions'] = array(
    '#type' => 'markup',
    '#value' => '<p>' . t('You need to grab the url to the profile you would like to link to. Find that by clicking the avatar and copy the long number in the address bar like the italicized part of this url: https://plus.google.com/<em>1234567890123456789</em>/posts.') . '</p>',
  );
  $form['plus_url_profile_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Google+ profile ID'),
    '#description' => t('The profile ID from Google+ you would like !site+ to redirect to.', array('!site' => url(NULL, array('absolute' => TRUE)))),
    '#default_value' => variable_get('plus_url_profile_id', ''),
  );
  $form['plus_url_section'] = array(
    '#type' => 'radios',
     '#title' => t('Section of the profile to link to'),
     '#description' => t('Choose wether you would like the link to go to the stream of the profile or the "about" page. Defaults to "about".'),
     '#options' => array('about' => t('About'), 'posts' => t('Posts (stream)')),
     '#default_value' => variable_get('plus_url_section', 'about'),
  );
  return system_settings_form($form);
}
