<?php

/**
 * @file
 * Redirect vBulletin URLs to Drupal.
 */

/**
 * Implementation of hook_perm().
 */
function vburls_perm() {
  return array('administer vburls');
}

/**
 * Implementation of hook_menu().
 */
function vburls_menu() {
  $items = array();

  $items['admin/config/vburls'] = array(
    'title' => 'vBURLs settings',
    'description' => 'Configuration of simple vBulletin/Photopost URL redirector.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vburls_admin_settings'),
    'access arguments' => array('administer vburls'),
    'file' => 'vburls.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $vbulletin_subdir = variable_get('vburls_vbulletin_subdir', '');
  $photopost_subdir = variable_get('vburls_photopost_subdir', '');
  if (!empty($vbulletin_subdir)) {
    $vbulletin_subdir .= '/';
  }
  if (!empty($photopost_subdir)) {
    $photopost_subdir .= '/';
  }

  if (variable_get('vburls_vbulletin_redirect', TRUE)) {
    foreach (array('showthread.php', 'forumdisplay.php') as $vb_file) {
      $items[$vbulletin_subdir . $vb_file] = array(
        'title' => 'vBulletin redirect',
        'access arguments' => array('access content'),
        'page callback' => 'vburls_simple_redirect',
        'type' => MENU_CALLBACK,
      );
    }
  }

  if (variable_get('vburls_photopost_redirect', TRUE)) {
    foreach (array('showphoto.php', 'showgallery.php') as $pp_file) {
      $items[$photopost_subdir . $pp_file] = array(
        'title' => 'Photopost redirect',
        'access arguments' => array('access content'),
        'page callback' => 'vburls_pp_simple_redirect',
        'page arguments' => array(1, 3),
        'type' => MENU_CALLBACK,
      );
    }
  }

  return $items;
}

/**
 * Perform redirect from Photopost URLs to Drupal.
 */
function vburls_pp_simple_redirect($pp_file, $value = NULL, $add_to_ids = PPTODRUPAL_ADD_TO_IDS) {
  if (empty($value) && empty($_GET['photo'])) {
    return drupal_not_found();
  }
  else if (empty($value) && !empty($_GET['photo'])) {
    $value = $_GET['photo'];
  }

  $drupal_mapping = array(
    'showphoto.php' => 'node',
    'showgallery.php' => 'taxonomy/term',
  );

  $value = (int) $value;
  if (empty($value)) {
    return drupal_not_found();
  }

  drupal_goto($drupal_mapping[$pp_file] . '/' . ($value + $add_to_ids));
}

/**
 * Page callback to perform simple redirection for t or p variables.
 */
function vburls_simple_redirect() {
  // Loop through possible vBulletin $_GET variables in order of preference.
  foreach (array(
    't' => 'node',
    'f' => 'forum',
  ) as $id => $url_prefix) {
    $value = (int) $_GET[$id];
    if (empty($value)) {
      continue;
    }

    drupal_goto($url_prefix . '/' . ($value + VBIMPORTAPI_ADD_TO_IDS));
  }
}
