<?php

/**
 * @file
 * The registry request module
 *
 * Adds request information to the registry
 */
/**
 * Implements hook_boot()
 *
 * Because we don't seem to be able to access arg() here, we do it ourselves.
 */
function registry_request_boot() {
  static $arguments;

  if (isset($_GET['q'])) {
    $path = $_GET['q'];
    $arguments[$path] = explode('/', $path);

    // Add path argument information
    include_once(dirname(__FILE__) . '/../registry.module');
    registry_set('path_arg', $arguments[$path]);
  }

  // Add path information
  if (isset($_GET['q'])) {
    registry_set('path', check_plain($_GET['q']));
  }
}

/**
 * Implements hook_init()
 */
function registry_request_init() {
  // Arguments
  $args = arg();
  registry_set('arg', $args);
}
