<?php
/**
 * @file
 * Module file for Drupal, required to be here.
 */

/**
 * Returns default value for module's inline conditions configure forms.
 * @param $settings
 * @return string
 */
function commerce_discount_product_category_configuration_default_value($settings) {
  $default_value = '';
  if (!empty($settings['terms'])) {
    foreach ($settings['terms'] as $delta => $term) {
      $default_value .= taxonomy_term_load($term['target_id'])->name . ' (' . $term['target_id'] . ')';
      if ($term != end($settings['terms'])) {
        $default_value .= ', ';
      }
    }
  }
  return $default_value;
}
