<?php
/**
 * @file
 * Main functions of the module.
 */

/**
 * Implementation of hook_menu().
 */
function block_tab_menu() {
  return array(
    'admin/config/system/block_tab' => array(
      'type' => MENU_NORMAL_ITEM,
      'title' => 'Block tab settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('block_tab_admin_settings'),
      'access arguments' => array('administer block tab settings'),
      'file' => 'block_tab.admin.inc',
      'description' => 'Administer Block Tab module settings',
    ),
  );
}


/**
 * Implementation of hook_perm().
 */
function block_tab_perm() {
  return array('
    administer block tab settings' => array(
      'title' => t('Administer block tabs'),
    ),
  );
}


/**
 * Implementation of hook_preprocess_ELEMENT().
 * 
 * @param array $vars 
 */
function block_tab_preprocess_block(&$vars) {
  $region_setting = variable_get('block_tab-regions', array());
  if ($region_setting[$vars['elements']['#block']->region]) {
    $vars['elements']['#block']->title = $vars['elements']['#block']->subject;
    $vars['elements']['#block']->subject = NULL;
  }
}


/**
 * Implementation of hook_preprocess_ELEMENT().
 */
function block_tab_preprocess_region(&$variables) {
  $path = drupal_get_path('module', 'block_tab');
  drupal_add_css($path . '/css/block_tab.css');
  drupal_add_js($path . '/js/block_tab.js');

  $region_setting = variable_get('block_tab-regions', array());
  $region = $variables['region'];
  if (isset($region_setting[$region]) && (string) $region_setting[$region] == $region) {
    $titles = array();
    $output = '';
    $first_flag = TRUE;

    foreach (element_children($variables['elements']) as $bid) {
      if (isset($variables['elements'][$bid]['#block'])) {

        $block = $variables['elements'][$bid]['#block'];
        $titles[] = array(
          'title' => empty($block->title) ? $bid : $block->title,
          'key' => $bid,
          'active' => $first_flag ? ' active' : '',
          'bid' => $block->bid,
        );

        $variables['elements'][$bid]['#block']->subject = '';
        $output .= '<div class="block_tab-block' . ($first_flag ? ' visible' : '') . '" id="block_tab-block-' . $bid . '">' . $variables['elements'][$bid]['#children'] . '</div>';

        $first_flag = FALSE;
      }
    }

    $title_html = '';
    foreach ((array) $titles as $title) {
      $title_html .= '<span class="block_tab-title' . $title['active'] . '" id="block_tab-title-' . $title['key'] . '" bid="' . $title['bid'] . '"><a href="#tab' . $title['bid'] . '">' . check_plain($title['title']) . '</a></span>';
    }

    $variables['content'] = '<div class="block_tab-titles" region="' . $region . '">' . $title_html . '</div>
          <div class="block_tab-blocks" region="' . $region . '">' . $output . '</div>';
  }
}
