<?php

/**
 * @file
 * cm_project_staff functions
 */

/**
 * Implements hook_menu().
 */
function cm_project_staff_menu() {
  $items = array();
  
  $items['admin/config/communitymedia/project/staff'] = array(
    'title' => 'Staff Settings',
    'description' => 'Configuration options for the Community Media Project.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cm_project_staff_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Builds the cm_project admininstration settings form.
 */
function cm_project_staff_admin_settings($form, &$form_state) {
  $form = array();

  $form['cm_project_staff_rename_author'] = array(
    '#type' => 'textfield',
    '#title' => t('Rename default Author field label to'),
    '#default_value' => variable_get('cm_project_staff_rename_author', 'Executive Producer'),
    '#description' => t('Common labels include Member Sponsoring Program, Project Manager, Primary Producer'),
  );
  
  $form['cm_project_staff_author_field_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Author Field Description'),
    '#default_value' => variable_get('cm_project_staff_author_field_description', 'Additional producers/members can only be added after the project is Active'),
    '#description' => t(''),
  );
    
  return system_settings_form($form);
}

/**
 * Implements hook_node_form_alter().
 */
function cm_project_staff_form_cm_project_node_form_alter(&$form, &$form_state) {
  if (user_access('edit any cm_project content')) {

    if (isset($form_state['node'])) {
      $node = (array) $form_state['node'] + (array) $form['#node'];
    }
    else {
      $node = $form['#node'];
    }
    $node = (object) $node;
    // Move the author field and set autocomplete and ahah handlers.
    // We do this here and not in after_build because the ahah hash is handled before after_build is called.
    $form['name'] = $form['author']['name'];
    $form['name']['#title'] = variable_get('cm_project_staff_rename_author', 'Project Owner');
    $form['name']['#weight'] = -99;
    $form['name']['#description'] = variable_get('cm_project_staff_author_field_description', 'Additional producers/members can only be added after the project is Active');
    if (module_exists('civicrm_user_reference')) {
      $form['name']['#autocomplete_path'] = 'civicrm_user_reference/autocomplete-nouid';
    }
    unset($form['author']['name']);

    $form['#prefix'] = '<div id="reservations-staff-edit-form-wrapper">';
    $form['#suffix'] = '</div>';
  }
}