<?php
/**
 * @file
 * Install and uninstall related functions.
 */

/**
 * Implements hook_enable().
 */
function uc_nab_transact_hpp_enable() {
  $t = get_t();

  drupal_set_message($t('NAB Transact HPP payment method enabled. Please review the <a href="@url">configuration</a>.', array('@url' => url('admin/store/settings/payment/method/uc_nab_transact_hpp'))));
}

/**
 * Implements hook_uninstall().
 */
function uc_nab_transact_hpp_uninstall() {
  // Remove our variables.
  $vars = array(
    'uc_nab_transact_hpp_vendor_name',
    'uc_nab_transact_hpp_method_title',
    'uc_nab_transact_hpp_refund_policy',
    'uc_nab_transact_hpp_privacy_policy',
    'uc_nab_transact_hpp_information_fields',
    'uc_nab_transact_hpp_suppress_field_names',
    'uc_nab_transact_hpp_return_link_text',
    'uc_nab_transact_hpp_payment_server',
    'uc_nab_transact_hpp_checkout_button',
    'uc_nab_transact_hpp_payment_alert',
    'uc_nab_transact_hpp_reply_link_allowed_ips',
  );

  db_delete('variable')
    ->condition('name', $vars, 'IN')
  ->execute();

  // Clear the cache after the fact or they live on for a random period.
  cache_clear_all('variables', 'cache_bootstrap');
}
