routes:
  admin/reports/documentation/go1_base:
    title: GO1 Base
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Reports\Routes', 'render']
    type: constant('MENU_LOCAL_TASK')
    weight: -200

  admin/reports/documentation/go1_base/routes:
    title: Routes
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Reports\Routes', 'render']
    type: constant('MENU_DEFAULT_LOCAL_TASK')

  admin/reports/documentation/go1_base/source:
    title: Modules List
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Reports\SourceCode\ModuleIndex', 'render']
    type: constant('MENU_LOCAL_TASK')
    weight: 100

  'admin/reports/documentation/go1_base/source/%':
    title: Source
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Reports\SourceCode', 'render', [5]]
    weight: 100

  admin/reports/documentation/go1_base/entity-templates:
    title: Entity templates
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Reports\Entity_Templates', 'render']
    type: constant('MENU_LOCAL_TASK')

  go1/icon:
    title: Icons
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Icons', 'renderServices']

  'go1/icon/%':
    title: Icons
    access arguments: ['go1-doc access']
    controller: ['Drupal\go1_ui\Controller\Icons', 'renderServiceSets']
    breadcrumbs:
      - ['Home', '<front>']
      - ['Icons', 'go1/icon']

  'go1/icon/%/%':
    title: Icons
    access arguments: ['go1-doc access']
    controller:
      - 'Drupal\go1_ui\Controller\Icons'
      - 'renderServiceSet'
      - { service_name: 2, set_name: 3 }
    before:
      - ['drupal_add_library', ['system', 'ui.dialog']]
    attached:
      css:
        - '%datatables/media/css/jquery.dataTables.css'
        - '@go1_ui/misc/css/go1.icon.css'
      js:
        - '%datatables/media/js/jquery.dataTables.min.js'
        - '@go1_ui/misc/js/go1.icon.js'
    breadcrumbs:
      - ['Home', '<front>']
      - ['Icons', 'go1/icon']

  go1/sql:
    title: Execute SQL Query
    # Permisison defined by devel.module
    access arguments: ['execute php code']
    file: go1_ui.go1sql.inc
    page callback: drupal_get_form
    page arguments: ['go1_ui_sql_form']
    before:
      - [go1_ui_include_codemirror, [['mode/sql/sql.js']]]
      - [drupal_add_js,  ['@go1_ui/misc/js/go1.sql.js']]
      - [drupal_add_css, ['@go1_ui/misc/css/cm.css']]

  go1/twig:
    title: Twig Form
    access arguments: ['execute php code']
    file: go1_ui.codemirror.go1twig.inc
    page callback: drupal_get_form
    page arguments: ['go1_ui_twig_form']
    form: 'Drupal\go1_ui\Controller\TwigFormController'
    form arguments: []
    before:
      - [go1_ui_include_codemirror, [['mode/htmlmixed/htmlmixed.js', 'mode/xml/xml.js', 'addon/mode/overlay.js']]]
      - [drupal_add_js, ['@go1_ui/misc/js/go1.twig.js']]
      - [drupal_add_css, ['@go1_ui/misc/css/cm.css']]

  go1/twig/views:
    title: drupalView
    access arguments: ['execute php code']
    file: go1_ui.codemirror.go1twig.inc
    page callback: drupal_get_form
    page arguments: ['go1_ui_twig_views_form']
