---
- name: Ensure Skynet's dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == 'Debian'
  with_items:
    - python-pip
    - python-dev
    - build-essential
    - python-mysqldb
    - supervisor

- name: Install Cement
  pip:
    name: cement
    state: present

- name: Allow 'aegir' user to restart Skynet queue
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-skynet"
    content: |
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl start skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl stop skynet-queue
     {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart skynet-queue\n
    mode: 0440

- name: Clone Skynet
  git:
    repo: "{{ skynet_repo }}"
    dest: "{{ aegir_root }}/.drush/skynet"
    depth: 1 # speeds things up
    version: "{{ skynet_version }}"
    update: "{{ skynet_update }}"
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  register: clone_skynet

- name: Flush Drush cache to pick up Skynet commandfile
  shell: drush cc drush
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  when: clone_skynet.changed

- name: Create Skynet config file
  shell: drush @hostmaster provision-verify
  args:
    creates: "{{ aegir_root }}/config/skynet.conf"
  sudo: yes
  sudo_user: "{{ aegir_user }}"

- name: Add Skynet Supervisor config
  template:
    src: skynet-queue.conf.j2
    dest: /etc/supervisor/conf.d/skynet-queue.conf
  notify: Reload Supervisor

- name: Start Skynet via Supervisor
  supervisorctl:
    name: skynet-queue
    state: started
