<?php
/**
 * @file
 * A codec module to allow ted videos to be embedded using
 * video filter module.
 */

/**
 * Implements hook_help().
 */
function video_filter_ted_help($path, $arg) {
  switch ($path) {
    case 'admin/help#video_filter_ted':
    $output = '';
    $output .= '<p>' . t('Video Filter Ted allows you to embed videos from Ted on your website using the Video Filter module.');
    $output .= '<h3>' . t('How to use the module') . '</h3>';
    $output .= '<ul>';
    $output .= '<li>' . t('Enable the module as you would any Drupal module.') . '</li>';
    $output .= '<li>' . t('On the text formats page make sure Video Filter is switched on.') . '</li>';
    $output .= '<li>' . t('In the list "Filter processing order", make sure video filter is after "Limit allowed HTML tags" and before "Convert URLs into links".') . '</li>';
    $output .= '<li>' . t('If using the wysiwyg module, make sure you enable the video filter button on the wysiwyg profile that you wish to use it for.') . '</li>';
    $output .= '</ul>';
    return $output;
  }
}

/**
 * Implements hook_codec_info().
 *
 * @see video_filter_codec_info().
 */
function video_filter_ted_codec_info() {
  $codecs = array();

  $codecs['ted'] = array(
    'name' => t('Ted'),
    'sample_url' => 'https://www.ted.com/talks/anand_giridharadas_a_tale_of_two_americas_and_the_mini_mart_where_they_collided',
    'callback' => 'video_filter_ted',
    'regexp' => '/ted\.com\/talks\/([a-zA-Z0-9\-_]+)/',
    'ratio' => 16 / 9,
    'control_bar_height' => 0,
  );

  return $codecs;
}

/**
 * Callback for ted Fullshow codec.
 *
 * @see video_filter_codec_info().
 */
function video_filter_ted($video) {
  $video['source'] = 'https://embed-ssl.ted.com/talks/' . $video['codec']['matches'][0] . '.html';
  // The above is puling in the url part of the regex, so we need to do a
  // search and replace to remove it.
  $toomuch = array("https://embed-ssl.ted.com/talks/ted.com/talks/");
  $justright   = array("https://embed-ssl.ted.com/talks/");
  $replaced = str_replace($toomuch, $justright, $video);
  $video = $replaced;

  return video_filter_iframe($video);
}
