<?php
/**
 * @file
 * Main hook implementations.
 */

/**
 * Implements template_process_html().
 */
function remysharp_html5shim_process_html(&$variables) {
  // The JavaScript file to load.
  $js = 'http://html5shim.googlecode.com/svn/trunk/html5.js';

  // Compile the necessary HTML code.
  $output = "\n";
  $output .= "<!--[if lt IE 9]>\n";
  $output .= "<script src=\"{$js}\"></script>\n";
  $output .= "<![endif]-->\n";

  // Add the code after the other scripts.
  $variables['scripts'] .= $output;
}
