<?php
/**
 * @file
 * Stomp module integrates Drupal with an external STOMP
 * message queue, such as ActiveMQ.
 */


/**
 * Get Queue Parameters
 *
 * @param $name
 *   The name of the queue to get parameters for.
 */
function stomp_get_queue_options($name) {
  static $options = array();

  if (!isset($options[$name])) {
    $options[$name] = variable_get('stomp_queue_' . $name, array());

    $defaults = variable_get('stomp_default_queue', array()) + array(
      'brokers' => variable_get('stomp_brokers', array('tcp://127.0.0.1:61613')),
      'randomize' => variable_get('stomp_failover_randomize', 'false'),
    );
    $options[$name] += $defaults;
  }

  return $options[$name];
}
