<?php

/**
 * @file
 * Install, update and uninstall functions for the Weblinks_Checker module.
 * Drupal 7 Version
 */

/**
 * Implements hook_enable().
 * Set our module weight.
 */
function weblinks_checker_enable() {
  db_query("UPDATE {system} SET weight=-2 WHERE type='module' AND name='weblinks_checker'");
}

/**
 * Implements hook_uninstall().
 */
function weblinks_checker_uninstall() {
  variable_del('weblinks_allow_dupes');
  variable_del('weblinks_checker_action_on_unpublished');
  variable_del('weblinks_checker_detail_log');
  variable_del('weblinks_checker_enabled');
  variable_del('weblinks_checker_ignore');
  variable_del('weblinks_checker_ignore_zero');
  variable_del('weblinks_checker_interval');
  variable_del('weblinks_checker_last');
  variable_del('weblinks_checker_limit');
  variable_del('weblinks_checker_order');
  variable_del('weblinks_checker_redirect');
  variable_del('weblinks_checker_show_status');
  variable_del('weblinks_checker_summary_msg');
  variable_del('weblinks_checker_unpublish');
  variable_del('weblinks_checker_unpublish_after');
  variable_del('weblinks_rescue_move');
  variable_del('weblinks_rescue_unpub');
  variable_del('weblinks_validate_check');
}

/**
 * Implements hook_update_last_removed().
 */
function weblinks_checker_update_last_removed() {
  return 6001;
}

/**
 * Delete variable 'weblinks_user_rescue' which is no longer used.
 */
function weblinks_checker_update_7000() {
  variable_del('weblinks_user_rescue');
}

/**
 * Fix inconsistencies between node status and node revision status.
 */
function weblinks_checker_update_7001() {
  // The checker used to only update the node table and did not keep the
  // node_revision table in line. If any weblinks nodes currently have this
  // inconsistency then fix them here. We could do a node_load and node_save
  // but that may trigger too many other unwanted actions, so just fix our
  // error directly in node_revision, using the status from the node table.
  // @see http://www.drupal.org/node/2415693
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'vid', 'title'));
  $query->addField('n', 'status', 'node_status');
  $query->addJoin('LEFT', 'node_revision', 'nr', 'n.nid = nr.nid and n.vid = nr.vid');
  $query->addField('nr', 'status', 'node_revision_status');
  $query->condition('n.type', 'weblinks');
  $query->where('n.status <> nr.status');
  $fixed = 0;
  foreach ($query->execute() as $row) {
    db_update('node_revision')
      ->fields(array('status' => $row->node_status))
      ->condition('nid', $row->nid)
      ->condition('vid', $row->vid)
      ->execute();
    $fixed++;
  }
  if ($fixed) {
    return format_plural($fixed, 'Fixed 1 Weblink in node_revision table.', 'Fixed @count Weblinks in node_revision table.');
  }
  else {
    return t('There were no Weblinks with inconsistent status values between the node and node_revision tables.');
  }

}
