<?php
/**
 * @file
 * Install file.
 */

/**
 * Implements hook_enable().
 */
function janrain_example_enable() {

  janrain_example_node_create();

  if (_janrain_is_login_only()) {
    menu_link_maintain('janrain_example', 'insert', 'user/login', 'Log in');
    menu_link_maintain('janrain_example', 'delete', 'user/login', 'Log in');
    return;
  }
}

/**
 * Implements hook_disable().
 */
function janrain_example_disable() {

  janrain_example_node_remove();

  menu_link_maintain('janrain_example', 'delete', 'user/login', 'Log in');
}

/**
 * Create the nodes for special interaction widgets.
 */
function janrain_example_node_create() {
  $body_text = 'Thank you for verifying your email.';

  $node = new stdClass();
  $node->type = 'page';
  node_object_prepare($node);

  $node->title    = 'Email Verified';
  $node->language = LANGUAGE_NONE;
  $node->comment = 0;
  $node->status = 1;
  $node->promote = 0;
  $node->sticky = 0;

  $node->body[$node->language][0]['value']   = $body_text;
  $node->body[$node->language][0]['summary'] = text_summary($body_text);
  $node->body[$node->language][0]['format']  = 'filtered_html';

  $path = 'janrain/verify_email';
  $node->path = array('alias' => $path);

  node_save($node);

  // Add password recovery page.
  $body_text = 'Recover/Reset your password.';
  $node = (object) array('type' => 'page');
  node_object_prepare($node);
  $node->title = 'Password Recovery';
  $node->language = LANGUAGE_NONE;
  $node->comment = 0;
  $node->status = 1;
  $node->promote = 0;
  $node->sticky = 0;
  $node->body[$node->language][0]['value']   = $body_text;
  $node->body[$node->language][0]['summary'] = text_summary($body_text);
  $node->body[$node->language][0]['format']  = 'filtered_html';
  $path = 'janrain/password_recover';
  $node->path = array('alias' => $path);
  node_save($node);
}

/**
 * Remove the nodes for special interaction widgets.
 */
function janrain_example_node_remove() {
  $page_title = 'Password Recovery';
  $sql = 'SELECT nid FROM {node} n WHERE n.title = :title';
  $result = db_query($sql, array(':title' => $page_title));
  $nodeids = array();
  foreach ($result as $row) {
    $nodeids[] = $row->nid;
  }
  $page_title = 'Email Verified';
  $sql = 'SELECT nid FROM {node} n WHERE n.title = :title';
  $result = db_query($sql, array(':title' => $page_title));
  foreach ($result as $row) {
    $nodeids[] = $row->nid;
  }
  node_delete_multiple($nodeids);
}
