<?php
/**
 * @file
 * Code for the Enterprise_images feature.
 */

include_once('enterprise_images.features.inc');


/**
 * Implements hook_enterprise_base_apps_structures()
 */
function enterprise_images_enterprise_base_apps_structures() {
  $structures = array();
  $structures['enterprise_images'] = array(
    'title' => t('Images'),
  );
  $visibility = array(
    'enterprise_images_view' => array(
      'title' => t('Show on image gallery pages'),
      'views' => array(
        'views' => array('enterprise_images:page'),
      ),
    ),
    'enterprise_images_content_type' => array(
      'title' => t('Show on image details pages'),
      'node_type' => array(
        'types' => array('enterprise_image'),
      )
    ),
  );

  $view = views_get_view('enterprise_images');
  $desc_block = isset($view->display['block']->display_options['display_description']) ? $view->display['block']->display_options['display_description'] : '';
  $desc_similar = isset($view->display['similar_block']->display_options['display_description']) ? $view->display['similar_block']->display_options['display_description'] : '';
  $desc_categories = isset($view->display['categories_block']->display_options['display_description']) ? $view->display['categories_block']->display_options['display_description'] : '';
  $desc_tags = isset($view->display['tags_block']->display_options['display_description']) ? $view->display['tags_block']->display_options['display_description'] : '';
  $structures['enterprise_images']['blocks'] = array(
    'views:enterprise_images-block' => array(
      'description' => $desc_block,
      'defaults' => array(
        'regions' => array('sidebar_second'),
        'visibility' => array('enterprise_images_content_type'),
      ),
      'visibility' => $visibility,
      'weight' => 1,
    ),
    'views:enterprise_images-similar_block' => array(
      'description' => $desc_similar,
      'defaults' => array(
        'regions' => array('sidebar_second'),
        'visibility' => array('enterprise_images_content_type'),
      ),
      'visibility' => $visibility,
      'weight' => 2,
    ),
    'views:enterprise_images-categories_block' => array(
      'description' => $desc_categories,
      'defaults' => array(
        'regions' => array('sidebar_first'),
        'visibility' => array('enterprise_images_view'),
      ),
      'visibility' => $visibility,
      'weight' => 3,
    ),
    'views:enterprise_images-tags_block' => array(
      'description' => $desc_tags,
      'defaults' => array(
        'regions' => array('sidebar_first'),
        'visibility' => array('enterprise_images_view'),
      ),
      'visibility' => $visibility,
      'weight' => 4,
    ),
    /**/
  );
  return $structures;   
}