<?php
/**
 * @file
 */

/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function ns_text_wysiwyg_editor_settings_alter(&$settings, &$context) {
  // CKeditor can use classes instead of inline css when using the justify
  // plugin and the indent plugin.
  if ($context['editor']['name'] == 'ckeditor') {
    // Use justify classes instead of inline css.
    $settings['justifyClasses'] = array(
      'align-left',
      'align-center',
      'align-right',
      'align-justify',
    );

    // Use indent classes instead of inline css.
    $settings['indentClasses'] = array(
      'indent-1',
      'indent-2',
      'indent-3',
      'indent-4',
    );

    // As we want to insert classes instead of inline css, we most have the
    // classes defined in a css file.

    // This is the default ckeditor css file.
    $settings['contentsCss'][] = base_path() . wysiwyg_get_path('ckeditor') . '/contents.css';
    // Add basic default styles. To override this, just override them in your
    // own theme css file.
    $settings['contentsCss'][] = base_path() . drupal_get_path('module', 'ns_text') . '/css/ns_text.css';

  }
}

/**
 * Implements hook_page_alter().
 */
function ns_text_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'ns_text') . '/css/ns_text.css', array('group' => CSS_SYSTEM));
}
