<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\plug_config\Plugin\PlugConfigManager;

/**
 * Implements hook_menu().
 */
function plug_config_example_menu() {
  if (module_exists('plug_example')) {
    $items['plug/test/config'] = array(
      'title' => 'Config',
      'description' => 'Plugins Config page.',
      'page callback' => 'plug_config_example_test_page',
      'access callback' => TRUE,
      'type' => MENU_LOCAL_TASK,
    );
    return $items;
  }
}

/**
 * Page callback to test the plugins.
 */
function plug_config_example_test_page() {
  $manager = PlugConfigManager::create();
  return plug_example_test_page_content($manager, 'getLabel');
}
