<?php

/**
 * Implements hook_feeds_plugins().
 */
function redhen_feeds_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugin().
 */
function redhen_feeds_feeds_plugins() {
  $info = array();
  $info['RedhenFeedsContactProcessor'] = array(
    'name' => 'RedHen Contact Processor',
    'description' => 'Import RedHen contacts',
    'help' => 'Creates or updates RedHen contacts from feeds.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'RedhenFeedsContactProcessor',
      'file' => 'RedhenFeedsContactProcessor.inc',
      'path' => drupal_get_path('module', 'redhen_feeds') . '/lib',
    ),
  );
  $info['RedhenFeedsOrgProcessor'] = array(
    'name' => 'RedHen Organization Processor',
    'description' => 'Import RedHen organizations',
    'help' => 'Creates or updates RedHen organizations from feeds.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'RedhenFeedsOrgProcessor',
      'file' => 'RedhenFeedsOrgProcessor.inc',
      'path' => drupal_get_path('module', 'redhen_feeds') . '/lib',
    ),
  );
  return $info;
}
