<?php

/**
 * Implements hook_services_resources().
 */
function commerce_drupalgap_stripe_services_resources() {
  $resources = array();
  // Define a resource for retrieving a collection of line items.
  $resources['commerce-payment-stripe'] = array(
    '#api_version' => 3002,
    'operations' => array(
      // Define the create callback for a POST to /payment.
      'create' => array(
        'help' => 'Creates a new payment transaction for an existing order.',
        'callback' => 'commerce_drupalgap_stripe_create',
        'file' => array('type' => 'inc', 'module' => 'commerce_drupalgap_stripe', 'name' => 'resources/payment'),
        'access callback' => 'commerce_drupalgap_stripe_create_access',
        'args' => array(
          // The data array must include at least an order_id and payment method or it
          // will result in an error.
          array(
            'name' => 'data',
            'type' => 'array',
            'description' => 'The payment transaction data to set on create.',
            'optional' => FALSE,
            'source' => 'data',
          ),
          array(
            'name' => 'flatten_fields',
            'type' => 'string',
            'description' => 'A string indicating whether or not field value arrays are flattened; accepts true or false.',
            'optional' => TRUE,
            'source' => array('param' => 'flatten_fields'),
            'default value' => 'true',
          ),
        ),
      ),
    ),
  );


  return $resources;
}
