<?php

/**
 * Implements hooh_block_info().
 */
function poll_blocks_block_info() {
  $query = db_select('node', 'n');
  $query->fields('n', array('nid', 'title'));
  $query->join('poll', 'p', 'p.nid = n.nid');
  $query->condition('n.status', 1);
  $query->condition('p.active', 1);
  
  $blocks = array();
  foreach ($query->execute() as $node) {
    $blocks[$node->nid] = array('info' => t('Poll') . ': ' . $node->title);
  }
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function poll_blocks_block_view($delta = '') {
  if (user_access('access content')) {
    $select = db_select('node', 'n');
    $select->join('poll', 'p', 'p.nid = n.nid');
    $select->fields('n', array('nid'))
      ->condition('n.nid', $delta)
      ->addTag('node_access');

    $record = $select->execute()->fetchObject();
    if ($record) {
      $poll = node_load($record->nid);
      if ($poll->nid) {
        $poll = poll_block_latest_poll_view($poll);
        $block['subject'] = t('Poll');
        $block['content'] = $poll->content;
        return $block;
      }
    }
  }
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function poll_blocks_contextual_links_view_alter(&$element, $items) {
  if (isset($element['#element']['#block']) && $element['#element']['#block']->module == 'poll_blocks') {
    $element['#links']['poll_blocks'] = array(
      'title' => t('Edit poll'),
      'href'  => 'node/' . $element['#element']['#block']->delta . '/edit',
    );
  }
}
