# Define the required gems for this theme.
# http://bundler.io/v1.3/gemfile.html

# Grab gems from the RubyGems server.
source 'https://rubygems.org'

# Use ~> to to allow newer minor versions within the same major version.
# Remove ~> to require a specific version.
gem 'compass', '~>0.12.2'
gem 'breakpoint', '~>2.0.7'
gem 'singularitygs', '~>1.1.2'
gem 'singularity-extras', '~>0.0.3'
