# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  ENV['VALKYRIE_PROJECT_PATH'] = File.dirname(File.expand_path(__FILE__))
  require_relative "../drush-aliases.rb"

end
