<?php
/**
 * @file
 * Contains Pictaculous install hooks.
 */

/**
 * Implements hook_install().
 */
function pictaculous_install() {
  // variable_set('pictaculous_api_version', '1.0');
	variable_set('pictaculous_api_url', 'http://pictaculous.com/api');
}

/**
 * Implements hook_uninstall().
 */
function pictaculous_uninstall() {
	// variable_set('pictaculous_api_version', '1.0');
	variable_del('pictaculous_api_url');
	variable_del('pictaculous_object');
}

