services:
  smartling.settings:
    class:              Drupal\smartling\Settings\SmartlingSettingsHandler

  smartling.log:
    class:              Drupal\smartling\Log\SmartlingLog
    arguments:          [@smartling.settings]

  smartling.api_wrapper:
    class:              Drupal\smartling\ApiWrapper\SmartlingApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.local_api_wrapper:
    class:              Drupal\smartling\ApiWrapper\SmartlingLocalApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.mock_api_wrapper:
    class:              Drupal\smartling\ApiWrapper\MockApiWrapper
    arguments:          [@smartling.settings, @smartling.log]

  smartling.field_processor_factory:
    class:              Drupal\smartling\FieldProcessorFactory
    arguments:          [%field_processors%, @smartling.log, @smartling.wrappers.field_api_wrapper, @smartling.wrappers.entity_api_wrapper, @smartling.wrappers.drupal_api_wrapper,@smartling.wrappers.smartling_utils]

  smartling.entity_processor_factory:
    class:              Drupal\smartling\EntityProcessorFactory
    arguments:          [%entity_processors%, @smartling.wrappers.drupal_api_wrapper]




  smartling.forms.admin_node_translation_settings:
    class:              Drupal\smartling\Forms\AdminNodeTranslationSettingsForm
    arguments:          [@smartling.settings, @smartling.log, @smartling.field_processor_factory]

  smartling.forms.admin_taxonomy_translation_settings:
    class:              Drupal\smartling\Forms\AdminTaxonomyTranslationSettingsForm
    arguments:          [@smartling.settings, @smartling.log, @smartling.field_processor_factory]

  smartling.forms.admin_entities_translation_settings:
    class:              Drupal\smartling\Forms\AdminEntitiesTranslationSettingsForm
    arguments:          [@smartling.settings, @smartling.log, @smartling.field_processor_factory]

  smartling.forms.admin_account_info_settings:
    class:              Drupal\smartling\Forms\AdminAccountInfoSettingsForm
    arguments:          [@smartling.settings, @smartling.api_wrapper]

  smartling.forms.admin_expert_settings:
    class:              Drupal\smartling\Forms\AdminExpertSettingsForm
    arguments:          [@smartling.settings, @smartling.log]


  smartling.forms.node_settings:
    class:              Drupal\smartling\Forms\NodeSettingsForm

  smartling.forms.comment_settings:
    class:              Drupal\smartling\Forms\CommentSettingsForm

  smartling.forms.taxonomy_term_settings:
    class:              Drupal\smartling\Forms\TaxonomyTermSettingsForm

  smartling.forms.user_settings:
    class:              Drupal\smartling\Forms\UserSettingsForm

  smartling.forms.generic_entity_settings:
    class:              Drupal\smartling\Forms\GenericEntitySettingsForm



  smartling.queue_managers.upload:
    class:              Drupal\smartling\QueueManager\UploadQueueManager
    arguments:          [@smartling.wrappers.smartling_submission_wrapper=, @smartling.entity_processor_factory, @smartling.settings, @smartling.wrappers.smartling_utils, @smartling.wrappers.drupal_api_wrapper, @smartling.utils.file_transport]

  smartling.queue_managers.download:
    class:              Drupal\smartling\QueueManager\DownloadQueueManager
    arguments:          [@smartling.wrappers.smartling_submission_wrapper=, @smartling.wrappers.field_api_wrapper, @smartling.entity_processor_factory, @smartling.wrappers.smartling_utils, @smartling.wrappers.drupal_api_wrapper, @smartling.utils.file_transport]

  smartling.queue_managers.check_status:
    class:              Drupal\smartling\QueueManager\CheckStatusQueueManager
    arguments:          [@smartling.api_wrapper, @smartling.wrappers.smartling_submission_wrapper=, @smartling.wrappers.entity_data_wrapper_collection, @smartling.queue_managers.download, @smartling.log, @smartling.wrappers.smartling_utils,  @smartling.wrappers.drupal_api_wrapper]

  smartling.queue_managers.bulk_check_status:
    class:              Drupal\smartling\QueueManager\BulkCheckStatusQueueManager
    arguments:          [@smartling.api_wrapper, @smartling.wrappers.smartling_submission_wrapper=, @smartling.wrappers.entity_data_wrapper_collection, @smartling.queue_managers.download, @smartling.log, @smartling.wrappers.smartling_utils,  @smartling.wrappers.drupal_api_wrapper]

  smartling.queue_managers.upload_router:
    class:              Drupal\smartling\QueueManager\UploadRouter
    arguments:          [@smartling.wrappers.entity_data_wrapper_collection, @smartling.queue_managers.upload, @smartling.log, @smartling.settings, @smartling.entity_conversion_utils.factory, @smartling.wrappers.smartling_utils]


  smartling.wrappers.smartling_submission_wrapper:
    class:              Drupal\smartling\Wrappers\SmartlingEntityDataWrapper
    arguments:          [@smartling.utils.file_name_manager]
    scope:              prototype

  smartling.wrappers.entity_data_wrapper_collection:
    class:              Drupal\smartling\Wrappers\SmartlingEntityDataWrapperCollection
    arguments:          [@smartling.wrappers.smartling_submission_wrapper=, @smartling.log, @smartling.wrappers.entity_api_wrapper]

  smartling.wrappers.entity_api_wrapper:
    class:              Drupal\smartling\Wrappers\EntityAPIWrapper

  smartling.wrappers.field_api_wrapper:
    class:              Drupal\smartling\Wrappers\FieldAPIWrapper

  smartling.wrappers.drupal_api_wrapper:
    class:              Drupal\smartling\Wrappers\DrupalAPIWrapper

  smartling.wrappers.smartling_utils:
    class:              Drupal\smartling\Wrappers\SmartlingUtils
    arguments:          [@smartling.wrappers.entity_api_wrapper, @smartling.wrappers.field_api_wrapper]

  smartling.wrappers.i18n_wrapper:
    class:              Drupal\smartling\Wrappers\InternationalizationWrapper


  smartling.utils.file_transport:
    class:              Drupal\smartling\Utils\FileTransport
    arguments:          [@smartling.settings, @smartling.api_wrapper, @smartling.wrappers.drupal_api_wrapper, @smartling.wrappers.smartling_utils]

  smartling.utils.file_name_manager:
    class:              Drupal\smartling\Utils\FileNameManager
    arguments:          [%entity_type_file_type_map%, @smartling.wrappers.drupal_api_wrapper]

  smartling.utils.cancel_submission:
    class:              Drupal\smartling\Utils\SmartlingCancelSubmission
    arguments:          [@smartling.log, @smartling.settings, @smartling.api_wrapper, @smartling.queue_managers.upload, @smartling.wrappers.smartling_submission_wrapper=]


  smartling.entity_conversion_utils.entity:
    class:              Drupal\smartling\EntityConversionUtils\EntityConversionUtil
    arguments:          [@smartling.settings, @smartling.wrappers.entity_api_wrapper, @smartling.wrappers.field_api_wrapper, @smartling.wrappers.drupal_api_wrapper, @smartling.wrappers.smartling_utils]

  smartling.entity_conversion_utils.node:
    class:              Drupal\smartling\EntityConversionUtils\NodeConversionUtil
    arguments:          [@smartling.settings, @smartling.wrappers.entity_api_wrapper, @smartling.wrappers.field_api_wrapper, @smartling.wrappers.drupal_api_wrapper, @smartling.wrappers.smartling_utils]

  smartling.entity_conversion_utils.factory:
    class:              Drupal\smartling\EntityConversionUtils\EntityConversionFactory

  smartling.entity_conversion_utils.taxonomy_term:
    class:              Drupal\smartling\EntityConversionUtils\TaxonomyTermConversionUtil



parameters:
  smartling_consider_log:   true

  entity_processors:
    node:                       Drupal\smartling\Processors\NodeProcessor
    taxonomy_term:              Drupal\smartling\Processors\TaxonomyTermProcessor
    smartling_interface_entity: Drupal\smartling\Processors\UIEntityProcessor
    generic:                    Drupal\smartling\Processors\GenericEntityProcessor

  field_processors:
    real:
      text:                 Drupal\smartling\FieldProcessors\TextFieldProcessor
      text_long:            Drupal\smartling\FieldProcessors\TextFieldProcessor
      text_with_summary:    Drupal\smartling\FieldProcessors\TextSummaryFieldProcessor
      image:                Drupal\smartling\FieldProcessors\ImageFieldProcessor
      field_collection:     Drupal\smartling\FieldProcessors\FieldCollectionFieldProcessor
      link_field:           Drupal\smartling\FieldProcessors\LinkFieldProcessor

    fake:
      title_property:       Drupal\smartling\FieldProcessors\TitlePropertyFieldProcessor
      title_property_field: Drupal\smartling\FieldProcessors\TitlePropertyFieldProcessor
      description_property_field: Drupal\smartling\FieldProcessors\DescriptionPropertyFieldProcessor
      name_property_field:  Drupal\smartling\FieldProcessors\NamePropertyFieldProcessor

  entity_type_file_type_map:
    smartling_interface_entity: gettext