<?php

/**
 * Implements hook_page_alter().
 *
 * This module works by adding to settings.php (recommended) or otherwise setting the following two variables:
 * 
 * enable_jira_issue_reporters : TRUE | FALSE -- setting this to TRUE will include any configured issue collectors on every page.
 *
 * jira_issue_repoters : array() -- An array of the JS file to include for each issue collector as provided by the HTML embed code from JIRA.
 *    Each item in the array should just be a string which contains the URL to the issue collector JS, eg:
 *    'http://jira.example.com/s/en_USh1u6hj/768/9/1.2.5/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?collectorId=5cbb920f'
 * 
 * Sample code for settings.php:
 * 
 * $conf['enable_jira_issue_reporters'] = TRUE;
 * $conf['jira_issue_reporters'] = array(
 *   'http://jira.example.com/s/en_USh1u6hj/768/9/1.2.5/_/download/batch/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector/com.atlassian.jira.collector.plugin.jira-issue-collector-plugin:issuecollector.js?collectorId=5cbb920f',
 * );
 */
function jira_issue_reporters_page_alter(&$page) {
  if (variable_get('enable_jira_issue_reporters', FALSE)) {

    $issue_reporters = variable_get('jira_issue_reporters', array());

    $processed_reporters = array();
    foreach ($issue_reporters as $issue_reporter) {
      $processed_reporters[$issue_reporter] = array('type' => 'external');
    }
    
    if (array_key_exists('#attached', $page['content'])) {
      if (array_key_exists('js', $page['#attached'])) {
        $page['content']['#attached']['js'] = array_merge($page['#attached']['js'], $processed_reporters);
      }
      else {
        $page['content']['#attached']['js'] = $processed_reporters;
      }

      if (array_key_exists('css', $page['#attached'])) {
        $page['content']['#attached']['css'] = array_merge($page['#attached']['css'], array(drupal_get_path('module', 'jira_issue_reporters') .'/jira_issue_reporters.css'));
      }
      else {
        $page['content']['#attached']['css'] = array(drupal_get_path('module', 'jira_issue_reporters') .'/jira_issue_reporters.css');
      }
    }
    else {
      $page['content']['#attached'] = array('js' => $processed_reporters, 'css' => array(drupal_get_path('module', 'jira_issue_reporters') .'/jira_issue_reporters.css'));
    }
  }
}