<?php
/**
 * @file
 * Field formatter for text fields that outputs encoded JSON.
 * Can be used when outputting json views via views_datasource.
 *
 * For options check php documentation:
 *   http://www.php.net/manual/en/function.json-encode.php
 */

/**
 * Implements hook_field_formatter_info().
 */
function json_field_formatter_field_formatter_info() {
  return array(
    'text_json' => array(
      'label' => t('JSON encoded'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function json_field_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Getting the actual value.
  foreach ($items as $delta => $item) {
    $value = $item['value'];
  }

  // Encode if we have a value.
  if (isset($value)) {
    $element[]['#markup'] = drupal_json_encode($value);
  }

  return $element;
}
