<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function zxcvbn_form_user_profile_form_alter(&$form) {
  $form['#attached']['js'][] = drupal_get_path('module', 'zxcvbn') .
    '/zxcvbn.js';
  $form['#attached']['js'][] = 'https://raw.github.com/lowe/zxcvbn/master/zxcvbn.js';
  // Translations.
  t('Instant');
  t('@t minutes');
  t('@t hours');
  t('@t days');
  t('@t months');
  t('@t years');
  t('Centuries');
  t('Time to crack:');
}
