<?php
/**
 * @file
 * showoff_demo_content.install
 */

/**
 * Implements hook_enable().
 */
function showoff_demo_content_enable() {
  $vocab = taxonomy_vocabulary_machine_name_load('feeds');
  if ($vocab === FALSE) {
    return;
  }
  $feed_category_term = (object) array(
    'name' => 'Example Category',
    'vid' => $vocab->vid,
  );
  taxonomy_term_save($feed_category_term);

  $unit = new stdClass();
  $unit->type = 'unit';
  node_object_prepare($unit);
  $unit->title = t('Test Unit using Simple Layout');
  $unit->body[LANGUAGE_NONE][0]['value'] = t('This is just a basic test unit that uses the provided Simple Fullscreen layout.');
  $unit->body[LANGUAGE_NONE][0]['format'] = filter_default_format();
  $unit->field_feeds[LANGUAGE_NONE][0]['layout'] = 'simple';
  $unit->field_feeds[LANGUAGE_NONE][0]['settings'] = array('feed-1' => 'feeds:feed_1');
  $unit->uid = 1;
  $unit->status = 1;
  $unit->language = LANGUAGE_NONE;
  node_save($unit);

  $fake_form_state = array(
    'values' => array(
      'feed_name' => 'Example Feed',
      'feed_machine_name' => 'example_feed',
      'feed_categories' => array(
        $feed_category_term->tid => $feed_category_term->tid,
      ),
    ),
  );
  showoff_feeds_feed_add_form_submit(array(), $fake_form_state);

  global $base_url;
  $picture_directory =  file_default_scheme() . '://images';
  if (file_prepare_directory($picture_directory, FILE_CREATE_DIRECTORY)){
    $picture_result = drupal_http_request($base_url . '/' . drupal_get_path('module', 'showoff_demo_content') . '/images/drupal.png');
    $picture_path = file_stream_wrapper_uri_normalize($picture_directory . '/drupal.png');
    $picture_file = file_save_data($picture_result->data, $picture_path, FILE_EXISTS_REPLACE);
    // Check to make sure the picture isn't too large for the site settings.
    $validators = array(
      'file_validate_is_image' => array(),
      'file_validate_image_resolution' => array('1920x1080'),
      'file_validate_size' => array(4000 * 1024),
    );
    $errors = file_validate($picture_file, $validators);
    if (empty($errors)) {
      $picture_file = file_save($picture_file);
      $image_node = new stdClass();
      $image_node->type = 'image';
      node_object_prepare($image_node);
      $image_node->title = t('Example Image');
      $image_node->body[LANGUAGE_NONE][0]['value'] = t('Just an example image node.');
      $image_node->body[LANGUAGE_NONE][0]['format'] = filter_default_format();
      $image_node->field_duration[LANGUAGE_NONE][0]['value'] = '15';
      $image_node->field_feed[LANGUAGE_NONE][0]['tid'] = $feed_category_term->tid;
      $image_node->field_date[LANGUAGE_NONE][0]['value'] = '2013-01-01 00:00:00';
      $image_node->field_date[LANGUAGE_NONE][0]['value2'] = '2014-01-01 00:00:00';
      $image_node->field_image[LANGUAGE_NONE][0] = array(
        'fid' => $picture_file->fid,
        'alt' => '',
        'title' => '',
        'width' => '1920',
        'height' => '1080',
        'uid' => $picture_file->uid,
        'filename' => $picture_file->filename,
        'uri' => $picture_file->uri,
        'filemime' => $picture_file->filemime,
        'filesize' => $picture_file->filesize,
        'status' => $picture_file->status,
        'timestamp' => $picture_file->timestamp,
      );
      $image_node->uid = 1;
      $image_node->status = 1;
      $image_node->language = LANGUAGE_NONE;
      node_save($image_node);
    }
  }
}

/**
 * Implements hook_disable().
 */
function showoff_demo_content_disable() {
  
}
