name = Lingotek App
description = The Lingotek Translation module makes it easy to instantly translate content directly within your Drupal site. Lingotek also provides professional translation services for organizations who need help getting their Drupal content translated. Our module seamlessly handles file transfer to translators, publication of translations on your Drupal site, and ongoing synchronization of your multilingual content.
machine_name = lingotek_app
version = 1.1
downloadable = lingotek_app 7.x-1.1
author = Lingotek
author_url = http://www.lingotek.com
screenshots[] = Translation.png
logo = lingotek-icon.png

dependencies[lingotek] = lingotek 7.x-5.09
dependencies[title] = title 7.x-1.0-alpha7
dependencies[i18n] = i18n 7.x-1.11
dependencies[variable] = variable 7.x-2.5
dependencies[entity] = entity 7.x-1.5
dependencies[views] = views 7.x-3.8
dependencies[l10n_update] = l10n_update 7.x-1.0
dependencies[ctools] = ctools 7.x-1.4
dependencies[potx] = potx 7.x-1.0

downloadables[lingotek_app 7.x-1.1] = http://ftp.drupal.org/files/projects/lingotek_app-7.x-1.1.tar.gz
downloadables[lingotek 7.x-5.09] = http://ftp.drupal.org/files/projects/lingotek-7.x-5.09.tar.gz
downloadables[title 7.x-1.0-alpha7] = http://ftp.drupal.org/files/projects/title-7.x-1.0-alpha7.tar.gz
downloadables[i18n 7.x-1.11] = http://ftp.drupal.org/files/projects/i18n-7.x-1.11.tar.gz
downloadables[variable 7.x-2.5] = http://ftp.drupal.org/files/projects/variable-7.x-2.5.tar.gz
downloadables[entity 7.x-1.5] = http://ftp.drupal.org/files/projects/entity-7.x-1.5.tar.gz
downloadables[views 7.x-3.8] = http://ftp.drupal.org/files/projects/views-7.x-3.8.tar.gz
downloadables[l10n_update 7.x-1.0] = http://ftp.drupal.org/files/projects/l10n_update-7.x-1.0.tar.gz
downloadables[ctools 7.x-1.4] = http://ftp.drupal.org/files/projects/ctools-7.x-1.4.tar.gz
downloadables[potx 7.x-1.0] =http://ftp.drupal.org/files/projects/potx-7.x-1.0.tar.gz
