<?php

/**
 * @file
 * Hook implementations and functions for providing
 * Views horizontal scroll pager.
 */

define('VIEWS_SCROLL_PAGER_JSCROLLPANE_MIN_PLUGIN_VERSION', '2.0.17');

/**
 * Implements hook_views_api().
 */
function views_scroll_pager_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_scroll_pager') . '/views',
  );
}

/**
 * Implements hook_theme().
 */
function views_scroll_pager_theme() {
  return array(
    'views_scroll_pager_horizontal_scroll' => array(
      'variables' => array(
        'element' => 0,
        'parameters' => array(),
        'views_class' => '',
        'navigation' => 0,
      ),
      'path' => drupal_get_path('module', 'views_scroll_pager') . '/theme',
      'file' => 'views_scroll_pager.theme.inc',
    ),
    'views_scroll_pager_layout' => array(
      'variables' => array(
        'pager_class' => '',
        'pager_items' => '',
        'total_pages' => '',
      ),
      'template' => 'theme/views-scroll-pager-layout',
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function views_scroll_pager_libraries_info() {
  $libraries['jscrollpane'] = array(
    'name' => 'jScrollPane  plugin',
    'vendor url' => 'http://jscrollpane.kelvinluck.com/',
    'download url' => 'http://jscrollpane.kelvinluck.com/#download',
    'version arguments' => array(
      'file' => 'jquery.jscrollpane.min.js',
      'pattern' => '@(?i:jScrollPane) - v([0-9\.a-z]+)@',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'jquery.jscrollpane.min.js',
      ),
      'css' => array(
        'jquery.jscrollpane.css',
      ),
    ),
  );

  return $libraries;
}
