<?php
/**
 * @file
 * Sets post-install messages and deletes variables when uninstalled.
 */

/**
 * Implements hook_install().
 */
function uptime_install() {
  $t = get_t();
  variable_set('uptime_ratio', $t('Error') . ' ');
  $text = $t('All pages now contain an uptime widget in the footer. !config_link and change the block settings at !blocks_link.', array(
    '!config_link' => l($t('Get an API key'), 'admin/config/system/uptime'),
    '!blocks_link' => l($t('Structure > Blocks > Uptime widget > Configure'), 'admin/structure/block/manage/uptime/uptime_widget/configure'),
    )
  );
  drupal_set_message($text);
}

/**
 * Implements hook_uninstall().
 */
function uptime_uninstall() {
  // Delete all variables set in variable table.
  db_delete('variable')
    ->condition('name', 'uptime_%', 'LIKE')
    ->execute();
  cache_clear_all('variables', 'cache_bootstrap');
}
