language: php
php:
  - 5.3
  - 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # ---------------------
  # Install Drush
  # ---------------------
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'create database drupal;'

before_script:
  # ---------------------
  # Variables
  # ---------------------
  - cd ..
  - export VENDOR=`pwd`
  - cd ..
  - export DRUPAL=`pwd`'/drupal/'

  # ---------------------
  # Download the codebase
  # ---------------------
  - wget https://github.com/mrsinguyen/go1test_profile/archive/master.zip
  - unzip -qq master
  - mv go1test_profile-master $DRUPAL
  - cd $DRUPAL
  - drush si testing --db-url=mysql://root:@localhost/drupal --yes
  - mv $VENDOR/* sites/all/modules/

  # ---------------------
  # Prepare env for the module
  # ---------------------
  - drush vset --yes file_temporary_path /tmp
  - drush en -y simpletest go1_base go1test_base

  # ---------------------
  # No cache data
  # ---------------------
  - drush cc all

script:
  - drush test-run --dirty --field-labels=0 'GO1 Unit'
  - drush test-run --dirty --field-labels=0 'GO1 Web'
