imports:
  - { resource: services.kv.yml }
  - { resource: services.cache.yml }
  - { resource: services.theming.yml }
  - { resource: services.helper.yml }
  - { resource: services.typeddata.yml }
  - { resource: services.icon.yml }

services:
  autoloader:
    class: 'Drupal\go1_base\Container\Autoloader'

  autoloader.psr0:
    class: 'Doctrine\Common\ClassLoader'
    file: '%doctrine_common/lib/Doctrine/Common/ClassLoader.php'

  expression_language:
    class: 'Symfony\Component\ExpressionLanguage\ExpressionLanguage'
    factory_class: 'GO1'
    factory_method: getExpressionLanguage

  breadcrumb_api:
    class: 'Drupal\go1_base\Helper\BreadcrumbAPI'
