services:
  type.any:
    class: Drupal\go1_base\TypedData\DataTypes\Any
    reuse: false
  type.boolean:
    class: Drupal\go1_base\TypedData\DataTypes\Boolean
    reuse: false
  type.integer:
    class: Drupal\go1_base\TypedData\DataTypes\Integer
    reuse: false
  type.string:
    class: Drupal\go1_base\TypedData\DataTypes\String
    reuse: false
  type.callable:
    class: Drupal\go1_base\TypedData\DataTypes\Kallable
    reuse: false
  type.function:
    class: Drupal\go1_base\TypedData\DataTypes\Fn
    reuse: false
  type.constant:
    class: Drupal\go1_base\TypedData\DataTypes\Constant
    reuse: false
  type.list:
    class: Drupal\go1_base\TypedData\DataTypes\ItemList
    reuse: false
  type.mapping:
    class: Drupal\go1_base\TypedData\DataTypes\Mapping
    reuse: false
