services:

  helper.controller.resolver:
    class: '\Drupal\go1_base\Helper\ControllerResolver'

  helper.content_render:
    reuse: false
    class: 'Drupal\go1_base\Helper\ContentRender'

  helper.real_path:
    class: 'Drupal\go1_base\Helper\RealPath'

  helper.timer:
    class: 'Drupal\go1_base\Helper\Timer'
