language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update
  - composer global require --prefer-source --no-interaction drush/drush:6.*

  # Build Codebase.
  - TESTDIR=$(pwd)
  - cd ..
  - drush dl --drupal-project-rename drupal
  - cd drupal

  # Disable sendmail (PHP)
  - if [[ "$TRAVIS_PHP_VERSION" = "php*" ]]; then echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  # Disable sendmail (HHVM)
  - if [[ "$TRAVIS_PHP_VERSION" = "hhv*" ]]; then echo sendmail_path=`which true` >> /etc/hhvm/php.ini; fi

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:
  - ln -s $TESTDIR sites/all/modules/commerce_reports

  # Update drupal core
  - drush si --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce" --yes
  - drush dl addressfield rules ctools entity views commerce charts date views_date_format_sql
  - drush en -y commerce_cart commerce_customer_ui commerce_product_ui commerce_line_item_ui commerce_order_ui commerce_payment commerce_payment_example commerce_tax_ui
  - drush en -y  commerce_reports simpletest

  # Start server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done

script:
  # Run the tests
  - drush test-run --uri=http://127.0.0.1:8888 "Commerce Reports"

  # Re-enable when trying to get CodeSniffer doesn't return a 403 anymore.
  #- /home/travis/.composer/vendor/bin/phpcs --standard=/home/travis/.composer/vendor/drupal/coder/coder_sniffer/Drupal --extensions=php,inc,test,module,install --ignore=css/ $TRAVIS_BUILD_DIR/../drupal/modules/search_api
