<?php
/**
 * @file
 */

/**
 * Implements hook_views_api().
 */
function views_access_callback_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Intermediary access callback function getting view arguments
 * and calling real function specified in view definition.
 */
function views_access_callback_access_callback($view_name, $display_id, $access_callback) {

  // Init view.
  $view = views_get_view($view_name);
  $view->set_display($display_id);
  $view->init_handlers();

  // Find the values for any arguments embedded in the path via '%'.
  $i = 0;
  foreach (explode('/', $view->display_handler->get_option('path')) as $element) {
    if ($element == '%') {
      $view->args[] = arg($i);
    }
    $i++;
  }
  // Now handle any implicit arguments from the end of the path.
  $num_arguments = count($view->argument);
  while (count($view->args) < $num_arguments) {
    $view->args[] = arg($i);
    $i++;
  }

  $result = FALSE;
  if (function_exists($access_callback)) {
    $result = call_user_func_array($access_callback, $view->args);
  }
  return $result;
}
