<!-- This is automatically generated by OM Subthemer module -->

<div class="wrapper-outer">
	<header id="header" class="wrapper wrapper-header"><div class="wrapper-inner">
		<?php print theme('identity', $identity_vars); ?>
		<?php print $header_block_region; ?>
    <div class="om-clearfix"></div>		
	</div></header><!-- /.wrapper-inner, /header -->
	<nav id="nav" class="wrapper wrapper-nav"><div class="wrapper-inner">
		<?php print theme('menu', $main_menu_vars); ?>
    <?php print theme('menu', $secondary_menu_vars); ?>
    <?php print $menu_bar_region; ?>      
	</div></nav><!-- /.wrapper-inner, /nav -->
	<?php print $highlighted_region; ?>
	<div class="wrapper wrapper-main"><div class="wrapper-inner">
		<?php print $sidebar_first_region; ?>
		<div class="wrapper wrapper-middle<?php print $wrapper_middle_grid; ?>">
			<?php print $breadcrumb; ?>
			<div class="wrapper-inner">
				<?php print theme('content_elements', $content_elements_vars); ?>
				<?php print render($page['help']); ?>
				<?php print $messages; ?>
				<?php print $content_region; ?>
				<?php print $feed_icons; ?>
			</div><!-- /.wrapper-inner -->
		</div><!-- /.wrapper-middle -->
		<?php print $sidebar_second_region; ?>
		<div class="om-clearfix"></div>
	</div></div><!-- /.wrapper-inner, /.wrapper-main -->
	<?php print $footer_region; ?>
</div><!-- /.wrapper-outer -->


