---
- name: Ensure Avahi-aliases' dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  when: ansible_os_family == 'Debian'
  with_items:
    - python-avahi
    - python-gobject
    - avahi-daemon
    - avahi-utils
    - supervisor

- name: Allow 'aegir' user to restart Avahi-aliases
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}-avahi"
    content: |
      {{ aegir_user }} ALL=NOPASSWD: /usr/bin/supervisorctl restart avahi-aliases\n
    mode: 0440

- name: Clone Avahi-aliases
  git:
    repo: "{{ valkyrie_avahi_repo }}"
    dest: "{{ aegir_root }}/.drush/provision_avahi"
    depth: 1 # speeds things up
    version: "{{ valkyrie_avahi_version }}"
    update: "{{ valkyrie_avahi_update }}"
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  notify:
    - Clear Drush cache
    - Verify Aegir front-end

- name: Ensure Aegir Avahi-aliases directory exists
  file:
    path: /var/aegir/config/avahi-aliases
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Ensure Avahi-aliases directory exists
  file:
    path: /etc/avahi/aliases.d
    state: directory

#- name: Create Skynet config file
#  meta: flush_handlers

- name: Add Avahi-aliases Supervisor config
  template:
    src: avahi-aliases.conf.j2
    dest: /etc/supervisor/conf.d/avahi-aliases.conf
  notify: Reload Supervisor

- name: Start Avahi-aliases via Supervisor
  supervisorctl:
    name: avahi-aliases
    state: started
