---
- name: Check for existing deploy keys
  stat:
    path: "{{ valkyrie_deploy_host_key_dir }}/{{ valkyrie_deploy_key_name }}"
  register: deploy_key_check

- name: Use existing keys and config, if they exist.
  copy:
    src: "{{ valkyrie_deploy_host_key_dir }}/"
    dest: "{{ valkyrie_deploy_key_dir }}"
  when: deploy_key_check.stat.exists

- name: Generate an SSH key-pair
  command: "ssh-keygen -q -t rsa -N '' -C '{{ valkyrie_deploy_comment }}' -f {{ valkyrie_deploy_key_dir }}/{{ valkyrie_deploy_key_name }}"
  args:
    creates: "{{ valkyrie_deploy_key_dir }}/{{ valkyrie_deploy_key_name }}"
    creates: "{{ valkyrie_deploy_key_dir }}/{{ valkyrie_deploy_key_name }}.pub"
  sudo: yes
  sudo_user: "{{ valkyrie_deploy_user }}"
  when: not deploy_key_check.stat.exists

- name: Add SSH config host entry
  template:
    src: ssh-config.j2
    dest: "{{ valkyrie_deploy_key_dir }}/config"
  sudo: yes

- name: Ensure proper ownership of SSH directory and files
  file:
    path: "{{ valkyrie_deploy_key_dir }}"
    owner: "{{ valkyrie_deploy_user }}"
    group: "{{ valkyrie_deploy_user }}"
    recurse: yes
  sudo: yes

- name: Secure SSH private key
  file:
    path: "{{ valkyrie_deploy_key_dir }}/{{ valkyrie_deploy_key_name }}"
    mode: 0600
  sudo: yes


- name: Check for indicator that we're running in a Vagrant VM.
  stat:
    path: /vagrant
  register: vagrant_vm_check

- name: Ensure SSH key backup directory exists
  file:
    path: "{{ valkyrie_deploy_host_key_dir }}"
    state: directory
  when: vagrant_vm_check.stat.exists

- name: Store backup of SSH keys and config on host machine
  copy:
    src: "{{ valkyrie_deploy_key_dir }}/"
    dest: "{{ valkyrie_deploy_host_key_dir }}"
  when: vagrant_vm_check.stat.exists and not deploy_key_check.stat.exists

- name: Retrieve SSH public key
  shell: "
  echo '/////////////////////////////////////////////////////////////////////////////';
  echo '  Add the following deploy key to your project on Github:';
  echo '=============================================================================';
  /bin/cat {{ valkyrie_deploy_key_dir }}/{{ valkyrie_deploy_key_name }}.pub;
  echo '=============================================================================';
  echo '/////////////////////////////////////////////////////////////////////////////';
  "
  register: ssh_public_key_output
  changed_when: False
