---
- name: Grant 'aegir' user access to system logs
  user:
    name: "{{ aegir_user }}"
    append: yes
    groups: adm

- name: Ensure 'aegir' user SSH dir exists
  file:
    path: /var/aegir/.ssh
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Check for host user SSH public key
  stat:
    path: /vagrant/.valkyrie/ssh/authorized_keys
  register: valkyrie_host_public_key_check

- name: Allow SSH as the 'aegir' user
  copy:
    src: /vagrant/.valkyrie/ssh/authorized_keys
    dest: /var/aegir/.ssh/authorized_keys
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  when: valkyrie_host_public_key_check.stat.exists

- name: Check if Valkyrie modules are enabled
  shell: "drush @hm pm-info --fields=status --format=list {{ item }} | egrep 'disabled|not installed'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valkyrie_modules_enabled
  with_items: valkyrie_modules
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Enable Valkyrie modules
  command: "drush @hm --yes en {{ item.1 }} --no-verify --strict=0"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  with_indexed_items: valkyrie_modules
  when: "valkyrie_modules_enabled.results[{{ item.0 }}].rc == 0"
  notify: Verify Aegir front-end

- name: Check if the cron-based task queue is enabled.
  shell: "drush @hm vget hosting_queue_tasks_enabled | grep 'false$'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valkyrie_cron_task_queue_check
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Disable cron-based task queue.
  command: drush @hm vset --format=boolean hosting_queue_tasks_enabled 0
  sudo: True
  sudo_user: "{{ aegir_user }}"
  when: valkyrie_cron_task_queue_check|failed

- name: Check if the default URL alias is set properly
  shell: "drush @hm vget hosting_alias_subdomain --exact | grep '^{{ ansible_domain }}$'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valkyrie_url_alias_check
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Set a default URL alias (based on the Facter-provided $domain)
  command: "drush @hm vset hosting_alias_subdomain {{ ansible_domain }}"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  when: valkyrie_url_alias_check|failed

- name: Check if sites can be deleted without first being disabled
  shell: "drush @hm vget hosting_require_disable_before_delete | grep 'false$'"
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: valkyrie_disable_before_delete_check
  changed_when: False
  failed_when: False
  ignore_errors: yes

- name: Allow site deletion without disabling first.
  command: drush @hm vset --format=boolean hosting_require_disable_before_delete 0
  sudo: True
  sudo_user: "{{ aegir_user }}"
  when: valkyrie_disable_before_delete_check|failed

- include: avahi.yml
  when: valkyrie_use_avahi == True

- include: deploy_keys.yml
  when: valkyrie_generate_deploy_keys == True

- name: Retrieve Aegir login link
  shell: "
  echo '/////////////////////////////////////////////////////////////////////////////';
  echo '  You can access the front-end of your Aegir install at:';
  echo '=============================================================================';
  drush @hm uli;
  echo '=============================================================================';
  echo '';
  echo '  ... or run: `drush @v uli`';
  echo '/////////////////////////////////////////////////////////////////////////////';
  "
  sudo: True
  sudo_user: "{{ aegir_user }}"
  register: aegir_login_link_output
  changed_when: False

- include: notifications.yml
  when: valkyrie_display_notifications == True


